Repository dream-num/univer, pull requests merged in 2024-04, with the labels that each got.

#1707 fix(sheets): fix the issue with selection during autofill
  packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
  packages/sheets-ui/src/commands/commands/auto-fill.command.ts
  packages/sheets-ui/src/controllers/auto-fill.controller.ts
Labels: qa:verified

#1762 feat(facade): add getSheetBySheetId API on FWorkbook
  packages/facade/src/apis/__tests__/facade.spec.ts
  packages/facade/src/apis/sheets/f-workbook.ts
  packages/facade/src/apis/sheets/f-worksheet.ts
Labels: scope:facade

#1714 fix(sheets): merge disappear on hide row
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-conditional-formatting/src/assets/icon-map.json
Labels: qa:verified

#1770 feat(facade): sheet api getId rename to getSheetId
  packages/facade/src/apis/__tests__/facade.spec.ts
  packages/facade/src/apis/sheets/f-worksheet.ts
Labels: scope:facade

#1636 fix(sheets): refactor mergecell generating logic
  packages/core/src/index.ts
  packages/core/src/services/undoredo/undoredo.service.ts
  packages/core/src/shared/__test__/object-matrix.spec.ts
  packages/core/src/shared/object-matrix.ts
  packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
  packages/sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
  packages/sheets/src/commands/commands/insert-row-col.command.ts
  packages/sheets/src/commands/commands/remove-row-col.command.ts
  packages/sheets/src/controllers/merge-cell.controller.ts
  packages/sheets/src/services/ref-range/ref-range.service.ts
  packages/sheets/src/services/sheet-interceptor/sheet-interceptor.service.ts
Labels: qa:verified

#1781 fix(sheet): data-validation delete mutation undo-redo
  packages/sheets-data-validation/src/models/sheet-data-validation-manager.ts
Labels: qa:verified

#1798 fix(formula): today fill error
  packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
  packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
Labels: qa:verified

#1799 fix(formula): bracket nested
  packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
  packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
Labels: qa:untested

#1717 fix(sheets): fix the issue where the editor position is incorrect after unmerging cells
  packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts
Labels: qa:verified

#1804 fix(sheets-ui): data-validation event bind timing
  packages/sheets-ui/src/controllers/cell-custom-render.controller.ts
  pnpm-lock.yaml
Labels: qa:verified

#1675 fix(docs): list indent and hanging
  examples/src/data/docs/default-document-data-cn.ts
  packages/docs/src/commands/commands/delete.command.ts
  packages/docs/src/commands/commands/list.command.ts
  packages/engine-render/src/basics/i-document-skeleton-cached.ts
  packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
  packages/engine-render/src/index.ts
Labels: qa:verified

#1765 fix(formula): copy paste range with formulas
  packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
  packages/engine-formula/src/engine/value-object/array-value-object.ts
  packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
  packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
  packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
Labels: qa:verified

#1711 feat(formula): add the Maxifs function
  packages/engine-formula/src/functions/statistical/function-map.ts
  packages/engine-formula/src/functions/statistical/maxifs/__tests__/index.spec.ts
  packages/engine-formula/src/functions/statistical/maxifs/index.ts
  packages/sheets-formula/src/locale/function-list/statistical/en-US.ts
  packages/sheets-formula/src/locale/function-list/statistical/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/statistical/zh-CN.ts
  packages/sheets-formula/src/services/function-list/statistical.ts
Labels: qa:verified

#1694 fix(formula): use ref range formula
  packages/core/src/shared/__test__/common.spec.ts
  packages/core/src/shared/common.ts
  packages/core/src/types/interfaces/i-range.ts
  packages/engine-formula/src/commands/mutations/set-array-formula-data.mutation.ts
  packages/engine-formula/src/commands/mutations/set-formula-data.mutation.ts
  packages/engine-formula/src/controller/calculate.controller.ts
  packages/engine-formula/src/index.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/engine-formula/src/models/utils/formula-data-util.ts
  packages/sheets-formula/README-zh.md
  packages/sheets-formula/README.md
  packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-formula/src/controllers/utils/__tests__/ref-range-formula.spec.ts
  packages/sheets-formula/src/controllers/utils/offset-formula-data.ts
  packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
  packages/sheets/src/commands/commands/delete-range-move-left.command.ts
  packages/sheets/src/commands/commands/delete-range-move-up.command.ts
  packages/sheets/src/commands/commands/insert-range-move-down.command.ts
  packages/sheets/src/commands/commands/insert-range-move-right.command.ts
  packages/sheets/src/commands/commands/insert-row-col.command.ts
  packages/sheets/src/commands/commands/move-range.command.ts
  packages/sheets/src/commands/commands/move-rows-cols.command.ts
  packages/sheets/src/commands/commands/remove-sheet.command.ts
  packages/sheets/src/commands/commands/set-worksheet-name.command.ts
Labels: qa:verified

#1784 feat(sheets): data-validation ref-range & optimize package orignize
  docs/tldr/ref-range/delete-range-move-other.tldr
  docs/tldr/ref-range/insert-range-move-other.tldr
  docs/tldr/ref-range/move-range-other.tldr
  docs/tldr/ref-range/move-rows-cols-other.tldr
  packages/data-validation/src/commands/mutations/formula.mutation.ts
  packages/data-validation/src/controllers/dv-resource.controller.ts
  packages/data-validation/src/controllers/dv-sheet.controller.ts
  packages/data-validation/src/index.ts
  packages/data-validation/src/models/data-validation-model.ts
  packages/data-validation/src/plugin.ts
  packages/data-validation/src/types/const/operator-text-map.ts
  packages/design/src/index.ts
  packages/sheets-data-validation/src/controllers/dv-model.controller.ts
  packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
  packages/sheets-data-validation/src/index.ts
  packages/sheets-data-validation/src/locale/en-US.ts
  packages/sheets-data-validation/src/locale/zh-CN.ts
  packages/sheets-data-validation/src/plugin.ts
  packages/sheets-data-validation/src/services/register-formula.service.ts
  packages/sheets-data-validation/src/validators/text-length-validator.ts
  packages/sheets-data-validation/src/views/item/index.module.less
  packages/sheets/src/index.ts
  packages/sheets/src/services/ref-range/__tests__/util.spec.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#1700 fix: display error in font family
  packages/ui/src/components/font-family/FontFamily.tsx
Labels: qa:verified

#1843 fix(sheets): inline format error in cell
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:verified

#1840 fix(sheets): auto height is not work when at default column width
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
Labels: qa:verified

#1842 fix: uniscript entry is displayed in zen mode
  examples/src/data/docs/default-document-data-en.ts
  examples/src/docs/main.ts
  packages/uniscript/src/controllers/menu.ts
Labels: qa:verified

#1838 feat(conditional-formatting): bugfix
  packages/engine-formula/src/index.ts
  packages/sheets-conditional-formatting-ui/src/commands/commands/add-data-bar-cf.command.ts
  packages/sheets-conditional-formatting-ui/src/commands/operations/open-conditional-formatting-panel.ts
  packages/sheets-conditional-formatting-ui/src/components/hook/useHighlightRange.ts
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/dataBar.tsx
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/highlightCell.tsx
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.module.less
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.module.less
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
  packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts
  packages/sheets-conditional-formatting-ui/src/locale/en-US.ts
  packages/sheets-conditional-formatting-ui/src/locale/zh-CN.ts
  packages/sheets-conditional-formatting/src/models/icon-map.ts
  packages/sheets-conditional-formatting/src/models/type.ts
  packages/sheets-conditional-formatting/src/render/type.ts
  packages/sheets-conditional-formatting/src/services/__test__/cf.service.spec.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/data-bar.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/highlight-cell.ts
  packages/sheets-conditional-formatting/src/services/conditional-formatting.service.ts
Labels: qa:verified

#1836 fix(docs): strikethrough position is incorrect
  examples/src/docs/main.ts
  packages/engine-render/src/basics/font-cache.ts
  packages/engine-render/src/basics/tools.ts
  packages/engine-render/src/components/docs/extensions/font-and-base-line.ts
  packages/engine-render/src/components/docs/extensions/line.ts
Labels: qa:verified

#1874 fix(sheets): the text is aligned at editorial and non-editorial states
  examples/src/data/docs/default-document-data-cn.ts
  packages/docs-ui/src/controllers/page-render.controller.ts
  packages/docs-ui/src/views/doc-canvas-view.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/docs/layout/doc-skeleton.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/services/editor-bridge.service.ts
  packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
  packages/sheets-ui/src/views/editor-container/index.module.less
  packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
Labels: qa:verified

#1885 fix(sheet-formula): fix error message on missing formula
  packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
  packages/engine-formula/src/engine/analysis/parser.ts
  packages/engine-formula/src/engine/ast-node/reference-node.ts
Labels: qa:verified

#1862 fix: text is cropped when rendered in italic style with background
  examples/src/data/docs/default-document-data-cn.ts
  packages/engine-render/src/basics/i-document-skeleton-cached.ts
  packages/engine-render/src/basics/interfaces.ts
  packages/engine-render/src/basics/tools.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/docs/extensions/background.ts
  packages/engine-render/src/components/docs/layout/model/glyph.ts
  packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
  packages/engine-render/src/components/docs/layout/tools.ts
Labels: qa:verified

#1729 fix(sheet): range selector drag row
  packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
  packages/sheets-ui/src/controllers/editor-bridge.controller.ts
  packages/sheets-ui/src/controllers/shortcuts/editor.shortcut.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
  packages/sheets/src/commands/commands/utils/selection-utils.ts
Labels: qa:rejected

#1897 fix(sheet): range selector error
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/views/defined-name/DefinedName.tsx
  packages/sheets-ui/src/views/defined-name/DefinedNameInput.tsx
  packages/sheets-ui/src/views/defined-name/index.module.less
  packages/ui/src/components/editor/TextEditor.tsx
  packages/ui/src/components/range-selector/RangeSelector.tsx
  packages/ui/src/services/layout/layout.service.ts
Labels: qa:verified

#1891 fix(conditional-formatting): disregarding computation beyond the tabl…
  packages/sheets-conditional-formatting/src/services/__test__/test.util.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/color-scale.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/data-bar.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/highlight-cell.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/icon-set.ts
  packages/sheets-conditional-formatting/src/services/calculate-unit/utils.ts
Labels: qa:verified

#1898 fix(conditional-formatting): gradient fills may conceal cell values
  packages/sheets-conditional-formatting-ui/src/controllers/cf.render.controller.ts
Labels: qa:verified

#1754 fix(sheet): fix some copy/paste bugs
  packages/core/src/shared/clipboard.ts
  packages/core/src/shared/common.ts
  packages/core/src/shared/index.ts
  packages/engine-numfmt/src/type.ts
  packages/engine-render/src/components/sheets/extensions/border.ts
  packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
  packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.copy-paste.controller.ts
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-alignment.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-border.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-font.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-form-excel.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-rotate.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
  packages/sheets-ui/src/services/clipboard/__tests__/constant.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts
  packages/sheets-ui/src/services/clipboard/type.ts
  packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
  packages/ui/src/utils/cell.ts
Labels: qa:verified

#1896 fix(sheets): refocus sheet cell when create new sheet
  packages/sheets-ui/src/controllers/editor-bridge.controller.ts
  packages/ui/src/services/layout/layout.service.ts
Labels: qa:verified

#1919 fix: the strickthough position is wrong when fontsize is different
  packages/engine-render/src/components/docs/extensions/line.ts
  packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
Labels: qa:verified

#1954 fix(sheet): header hidden
  examples/src/slides/main.ts
  packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
  packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
Labels: qa:untested

#1638 perf(formula): dependency maintain
  packages/engine-formula/src/basics/common.ts
  packages/engine-formula/src/controller/set-dependency.controller.ts
  packages/engine-formula/src/controller/set-other-formula.controller.ts
  packages/engine-formula/src/engine/dependency/dependency-tree.ts
  packages/engine-formula/src/engine/dependency/formula-dependency.ts
  packages/engine-formula/src/engine/value-object/array-value-object.ts
  packages/engine-formula/src/functions/base-function.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/engine-formula/src/models/utils/formula-data-util.ts
  packages/engine-formula/src/plugin.ts
  packages/engine-formula/src/services/dependency-manager.service.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-formula/src/controllers/utils/__tests__/offset-formula-data.spec.ts
  packages/sheets-formula/src/controllers/utils/__tests__/redo-undo-formula-data.spec.ts
  packages/sheets-formula/src/controllers/utils/offset-formula-data.ts
  packages/sheets-formula/src/controllers/utils/redo-undo-formula-data.ts
  packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
Labels: qa:verified

#1969 fix(conditional-formatting): create cf rule error
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
Labels: qa:verified

#1915 feat(data-validation): transform support for data validation
  examples/src/data/sheets/demo/default-workbook-data-validation.ts
  packages/data-validation/package.json
  packages/data-validation/src/commands/mutations/data-validation.mutation.ts
  packages/data-validation/src/common/util.ts
  packages/data-validation/src/models/data-validation-manager.ts
  packages/data-validation/src/models/data-validation-model.ts
  packages/data-validation/src/plugin.ts
  packages/data-validation/src/types/interfaces/i-formula-input.ts
  packages/design/src/components/draggable-list/DraggableList.tsx
  packages/design/src/components/popup/RectPopup.tsx
  packages/sheets-data-validation/src/controllers/dv-ref-range.controller.ts
  packages/sheets-data-validation/src/locale/en-US.ts
  packages/sheets-data-validation/src/locale/zh-CN.ts
  packages/sheets-data-validation/src/models/sheet-data-validation-manager.ts
  packages/sheets-data-validation/src/services/register-formula.service.ts
  packages/sheets-data-validation/src/validators/list-multiple-validator.ts
  packages/sheets-data-validation/src/validators/list-validator.ts
  packages/sheets-data-validation/src/views/detail/index.tsx
  packages/sheets-data-validation/src/views/formula-input/custom-formula-input.tsx
  packages/sheets-data-validation/src/views/formula-input/index.module.less
  packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx
  packages/sheets-data-validation/src/widgets/dropdown-multiple-widget.ts
  packages/sheets-ui/src/services/canvas-pop-manager.service.ts
  packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
Labels: qa:verified

#2021 fix(sheet): add cell custom field
  packages/core/src/types/interfaces/i-cell-data.ts
  packages/sheets-ui/src/locale/en-US.ts
  packages/sheets-ui/src/locale/zh-CN.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets/src/commands/commands/copy-worksheet.command.ts
  packages/sheets/src/commands/commands/insert-range-move-down.command.ts
  packages/sheets/src/commands/commands/insert-range-move-right.command.ts
  packages/sheets/src/commands/commands/insert-sheet.command.ts
  packages/sheets/src/commands/commands/move-range.command.ts
  packages/sheets/src/commands/commands/move-rows-cols.command.ts
  packages/sheets/src/commands/commands/set-worksheet-hide.command.ts
  packages/sheets/src/locale/en-US.ts
  packages/sheets/src/locale/zh-CN.ts
Labels: qa:verified

#1934 feat(sheet): force string adds popup
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
  packages/sheets-ui/src/controllers/force-string-alert.controller.ts
  packages/sheets-ui/src/controllers/force-string-render.controller.ts
  packages/sheets-ui/src/controllers/utils/__tests__/cell-tools.spec.ts
  packages/sheets-ui/src/controllers/utils/cell-tools.ts
  packages/sheets-ui/src/locale/en-US.ts
  packages/sheets-ui/src/locale/zh-CN.ts
  packages/sheets-ui/src/sheets-ui-plugin.ts
Labels: qa:verified

#1904 fix: replace whitespace characters in html str
  packages/core/src/shared/common.ts
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-font.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-form-excel.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts
  packages/ui/src/utils/cell.ts
Labels: qa:verified

#1970 feat(formula): add the Lower function
  packages/engine-formula/src/functions/text/function-map.ts
  packages/engine-formula/src/functions/text/lower/__test__/index.spec.ts
  packages/engine-formula/src/functions/text/lower/index.ts
  packages/sheets-formula/src/locale/function-list/text/en-US.ts
  packages/sheets-formula/src/locale/function-list/text/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/text/zh-CN.ts
  packages/sheets-formula/src/services/function-list/text.ts
Labels: qa:verified

#1945 feat(numfmt): refactor the numfmt model
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/core/src/types/interfaces/__tests__/i-cell-data.spec.ts
  packages/core/src/types/interfaces/i-style-data.ts
  packages/engine-formula/src/basics/common.ts
  packages/engine-formula/src/commands/mutations/set-formula-calculation.mutation.ts
  packages/engine-formula/src/commands/mutations/set-numfmt-formula-data.mutation.ts
  packages/engine-formula/src/controller/calculate.controller.ts
  packages/engine-formula/src/controller/formula.controller.ts
  packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
  packages/engine-formula/src/engine/ast-node/reference-node.ts
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
  packages/engine-formula/src/engine/reference-object/cell-reference-object.ts
  packages/engine-formula/src/engine/utils/__tests__/value-object.spec.ts
  packages/engine-formula/src/engine/utils/value-object.ts
  packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
  packages/engine-formula/src/functions/information/isref/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/column/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/columns/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/index/__test__/index.spec.ts
  packages/engine-formula/src/functions/lookup/indirect/__test__/index.spec.ts
  packages/engine-formula/src/functions/lookup/offset/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/row/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/rows/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/subtotal/__tests__/index.spec.ts
  packages/engine-formula/src/index.ts
  packages/engine-formula/src/models/__tests__/formula-data.model.spec.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/engine-formula/src/services/current-data.service.ts
  packages/engine-formula/src/services/runtime.service.ts
  packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
  packages/sheets-formula/src/controllers/array-formula-display.controller.ts
  packages/sheets-formula/src/controllers/numfmt-formula-display.controller.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-formula/src/formula-ui-plugin.ts
  packages/sheets-numfmt/src/controllers/__tests__/auto-fill.controller.spec.ts
  packages/sheets-numfmt/src/controllers/__tests__/cell-content.controller.spec.ts
  packages/sheets-numfmt/src/controllers/__tests__/copy-paste.controller.spec.ts
  packages/sheets-numfmt/src/controllers/__tests__/editor.controller.spec.ts
  packages/sheets-numfmt/src/controllers/numfmt.auto-fill.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.copy-paste.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.ref-range.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.sheet.controller.ts
  packages/sheets-numfmt/src/menu/menu.ts
  packages/sheets-numfmt/src/numfmt-plugin.ts
  packages/sheets-numfmt/src/utils/pattern.ts
  packages/sheets/package.json
  packages/sheets/src/basics/__tests__/numfmt-kit.spec.ts
  packages/sheets/src/basics/numfmt-kit.ts
  packages/sheets/src/commands/mutations/numfmt-mutation.ts
  packages/sheets/src/controllers/calculate-result-apply.controller.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/__tests__/numfmt.service.test.ts
  packages/sheets/src/services/numfmt/numfmt.service.ts
  packages/sheets/src/services/numfmt/type.ts
  pnpm-lock.yaml
Labels: qa:verified

#2034 fix(render-engine): punctuation render error in sheet cell
  packages/engine-render/src/basics/draw.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/docs/layout/tools.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
Labels: qa:verified

#1985 feat(formula): formula calculation progress
  examples/src/sheets/main.ts
  packages/sheets-formula/src/controllers/array-formula-display.controller.ts
  packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-ui/src/views/defined-name/index.module.less
  packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
  packages/sheets-ui/src/views/sheet-container/SheetContainer.tsx
  packages/ui/src/components/progress-bar/ProgressBar.tsx
  packages/ui/src/components/progress-bar/index.module.less
  packages/ui/src/index.ts
  packages/ui/src/services/__tests__/progress.service.spec.ts
  packages/ui/src/services/progress/progress.service.ts
  packages/ui/src/ui-plugin.ts
Labels: qa:verified

#2058 fix(sheet): cell custom supports updating from mutation
  packages/core/src/types/interfaces/i-cell-data.ts
  packages/sheets/src/commands/commands/__tests__/set-range-values.command.spec.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:verified

#2082 fix(sheets-data-validation): fix reject input incorrect
  packages/sheets-data-validation/src/controllers/dv-reject-input.controller.ts
  pnpm-lock.yaml
Labels: qa:verified

#2075 fix(sheets-ui): after unhiding row or col icon doesn't disappear
  packages/sheets-ui/src/controllers/header-unhide.render-controller.ts
Labels: qa:verified

#2086 fix(ui): fix close ui plugin config and focus capturing
  packages/ui/src/render-unit/.gitkeep
  packages/ui/src/services/layout/layout.service.ts
  packages/ui/src/ui-plugin.ts
Labels: qa:verified

#2076 feat(facade): workbook and worksheet operation
  examples/src/sheets/main.ts
  packages/facade/src/apis/__tests__/facade.spec.ts
  packages/facade/src/apis/facade.ts
  packages/facade/src/apis/sheets/__tests__/f-workbook.spec.ts
  packages/facade/src/apis/sheets/__tests__/f-worksheet.spec.ts
  packages/facade/src/apis/sheets/f-workbook.ts
  packages/facade/src/apis/sheets/f-worksheet.ts
Labels: qa:verified

#2092 fix: skeleton change will remove autofill popupmenu
  packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx
Labels: qa:verified

#1929 fix(sheet): set bottom by default for vertical align
  packages/engine-formula/src/engine/dependency/dependency-tree.ts
  packages/sheets-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#2126 fix(sheets-data-validation): data validation daily bugifx
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/engine-render/src/components/sheets/extensions/custom.ts
  packages/engine-render/src/components/sheets/extensions/marker.ts
  packages/sheets-data-validation/src/controllers/dv-alert.controller.ts
  packages/sheets-data-validation/src/controllers/dv-reject-input.controller.ts
  packages/sheets-data-validation/src/validators/date-validator.ts
  packages/sheets-data-validation/src/validators/decimal-validator.ts
  packages/sheets-data-validation/src/validators/text-length-validator.ts
  packages/sheets-data-validation/src/validators/whole-validator.ts
  packages/sheets-data-validation/src/views/date-dropdown/index.tsx
  packages/sheets-data-validation/src/views/formula-input/list-formula-input.tsx
  packages/sheets-data-validation/src/widgets/dropdown-multiple-widget.ts
  packages/sheets-data-validation/src/widgets/dropdown-widget.ts
Labels: qa:verified
