Repository dream-num/univer, pull requests merged in 2024-03, with the labels that each got.

#1442 refactor: update dom cursor to canvas cursor
  packages/engine-render/src/basics/range.ts
  packages/engine-render/src/components/docs/common/text-range.ts
  packages/engine-render/src/components/docs/text-selection-render-manager.ts
Labels: qa:verified

#1440 fix(design): fix z-index for `SubMenu`
  packages/design/src/components/menu/index.module.less
Labels: qa:verified

#1488 fix(doc): copy error when range is empty
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
Labels: qa:verified

#1487 fix(doc): need to serialize text ranges
  packages/docs/src/commands/commands/inline-format.command.ts
Labels: qa:verified

#1480 fix(sheet): inline format error when textRuns is empty
  examples/src/docs/main.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:verified

#1350 fix(sheet): insert row/col undo bug
  packages/sheets/src/commands/commands/insert-row-col.command.ts
Labels: qa:verified, pr:need-auto-tests

#1475 fix(sheets-ui): dynamically adjust row header width
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
Labels: qa:verified

#1477 fix(sheet): fix unreasonable merged selections
  packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
  packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
  packages/sheets-ui/src/commands/commands/utils/selection-utils.ts
Labels: qa:verified

#1464 fix(sheet): insert row col with effect freeze
  packages/sheets-ui/src/controllers/freeze.controller.ts
Labels: qa:verified

#1493 fix(formula): isMatchWildcard escape regular string, add icons
  packages/engine-formula/src/engine/utils/__tests__/compare.spec.ts
  packages/engine-formula/src/engine/utils/compare.ts
  packages/network/src/index.ts
  packages/ui/src/common/component-manager.ts
Labels: qa:untested

#1417 refactor(clipboard): always use native event for pasting
  packages/docs-ui/src/controllers/clipboard.controller.ts
  packages/sheets-ui/src/commands/commands/clipboard.command.ts
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/locale/en-US.ts
  packages/sheets-ui/src/locale/zh-CN.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/utils.ts
  packages/ui/src/controllers/shared-shortcut.controller.ts
  packages/ui/src/index.ts
Labels: qa:verified

#1499 fix(editor): cursor and menu and single choice
  examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
  packages/core/src/shared/compare.ts
  packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
  packages/ui/src/components/editor/TextEditor.tsx
  packages/ui/src/components/range-selector/RangeSelector.tsx
  packages/ui/src/services/editor/editor.service.ts
Labels: qa:untested

#1500 fix(sheet): add focus change
  examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
  packages/ui/src/components/editor/TextEditor.tsx
  packages/ui/src/components/range-selector/RangeSelector.tsx
Labels: qa:untested

#1473 fix(doc): copy form univer text and paste to univer
  examples/src/data/docs/default-document-data-cn.ts
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/paste-plugins/plugin-univer.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/utils.ts
  packages/docs-ui/src/services/clipboard/udm-to-html/__test__/convertor.spec.ts
  packages/docs-ui/src/services/clipboard/udm-to-html/convertor.ts
Labels: qa:verified

#1507 fix(editor): controlled component and readonly
  examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
  packages/docs-ui/src/controllers/text-selection.controller.ts
  packages/ui/src/components/editor/TextEditor.tsx
  packages/ui/src/components/range-selector/RangeSelector.tsx
  packages/ui/src/services/editor/editor.service.ts
Labels: qa:untested

#1511 fix(render): rect blurring
  packages/engine-render/src/basics/draw.ts
  packages/engine-render/src/components/docs/extensions/background.ts
  packages/engine-render/src/components/docs/extensions/line.ts
  packages/engine-render/src/components/sheets/extensions/background.ts
  packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/extensions/row-header-layout.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/context.ts
Labels: qa:untested

#1512 fix(editor): add value
  examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
  packages/ui/src/components/range-selector/RangeSelector.tsx
Labels: qa:untested

#1514 fix(editor): value change
  packages/ui/src/components/editor/TextEditor.tsx
Labels: qa:untested

#1517 fix(sheet): wrap and rotation
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
Labels: qa:untested

#1527 fix(sheet): the icons for hiding rows and columns do not disappear.
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/core/src/types/interfaces/i-column-data.ts
  packages/core/src/types/interfaces/i-row-data.ts
  packages/sheets-ui/src/controllers/header-unhide.controller.ts
Labels: qa:untested

#1525 fix(sheet): string bool and number align
  packages/core/src/types/interfaces/i-document-data.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
Labels: qa:untested

#1533 fix(sheet): editor error
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
Labels: qa:untested

#1535 fix: system shortcut teminate ime input
  packages/docs/src/controllers/ime-input.controller.ts
Labels: qa:untested

#1537 fix(sheet): merge align
  packages/engine-render/src/components/sheets/extensions/font.ts
Labels: qa:untested

#1538 fix(sheet): first sheet hidden
  packages/core/src/sheets/workbook.ts
Labels: qa:untested

#1539 fix(sheet): border excel compatibility
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/core/src/index.ts
  packages/core/src/shared/color/color-kit.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets/src/commands/commands/set-border-command.ts
Labels: qa:untested

#1545 fix(render): update font offset
  packages/engine-render/src/components/sheets/extensions/font.ts
Labels: qa:untested

#1565 fix(formula): worker error
  packages/engine-formula/src/basics/common.ts
  packages/engine-formula/src/basics/runtime.ts
  packages/engine-formula/src/commands/mutations/set-formula-calculation.mutation.ts
  packages/engine-formula/src/controller/calculate.controller.ts
  packages/sheets/src/controllers/calculate-result-apply.controller.ts
Labels: qa:untested

#1567 fix(sheet): border corner
  packages/engine-render/src/basics/draw.ts
  packages/engine-render/src/components/docs/extensions/border.ts
  packages/engine-render/src/components/sheets/extensions/border.ts
  packages/engine-render/src/context.ts
Labels: qa:untested

#1568 fix(editor): range selector
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor-bridge.controller.ts
  packages/sheets/src/commands/commands/set-border-command.ts
  packages/ui/src/components/range-selector/RangeSelector.tsx
  packages/ui/src/services/range-selector/range-selector.service.ts
Labels: qa:untested

#1571 feat(editor): style and placeholder
  examples/src/plugins/debugger/views/test-editor/TestTextEditor.tsx
  packages/ui/src/components/editor/TextEditor.tsx
  packages/ui/src/components/editor/index.module.less
  packages/ui/src/components/range-selector/RangeSelector.tsx
  packages/ui/src/components/range-selector/index.module.less
  packages/ui/src/locale/en-US.ts
  packages/ui/src/locale/zh-CN.ts
  packages/ui/src/services/editor/editor.service.ts
Labels: qa:untested

#1572 fix(sheet): selection color
  packages/sheets/src/basics/selection.ts
Labels: qa:untested

#1543 fix(formula): check syntax
  packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
  packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
  packages/engine-formula/src/engine/ast-node/function-node.ts
Labels: qa:untested

#1562 fix(sheet): keep consistent with excel rotation
  packages/engine-render/src/basics/text-rotation.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/interfaces.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
Labels: qa:verified

#1579 fix(formula): token uppercase
  packages/engine-formula/src/engine/analysis/__tests__/create-command-test-bed.ts
  packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
  packages/engine-formula/src/engine/ast-node/function-node.ts
  packages/engine-formula/src/engine/ast-node/reference-node.ts
Labels: qa:untested

#1560 fix: inline format in cell with rich text
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:verified

#1482 fix(sheet): inline format menu display error when paste
  packages/core/src/sheets/range.ts
  packages/sheets-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#1516 fix(sheets-ui): fix z-index value in operate-container
  packages/sheets-ui/src/views/operate-container/index.module.less
Labels: qa:verified

#1581 fix(formula): math functions support string number calculation
  packages/engine-formula/src/engine/value-object/__tests__/array-value-divided.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-minus.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-multiply.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-plus.spec.ts
  packages/engine-formula/src/engine/value-object/array-value-object.ts
  packages/engine-formula/src/engine/value-object/base-value-object.ts
  packages/engine-formula/src/functions/base-function.ts
  packages/engine-formula/src/functions/math/abs/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/abs/index.ts
  packages/engine-formula/src/functions/math/acos/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/acos/index.ts
  packages/engine-formula/src/functions/math/acosh/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/acosh/index.ts
  packages/engine-formula/src/functions/math/acot/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/acot/index.ts
  packages/engine-formula/src/functions/math/mod/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/mod/index.ts
  packages/engine-formula/src/functions/math/power/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/power/index.ts
  packages/engine-formula/src/functions/math/product/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/sum/index.ts
  packages/engine-formula/src/functions/statistical/counta/index.ts
Labels: qa:verified

#1605 fix(sheets): boolean should store as number
  .github/pull_request_template.md
  packages/core/src/index.ts
  packages/core/src/sheets/__tests__/worksheet.spec.ts
  packages/core/src/sheets/worksheet.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:untested

#1616 fix(editor): optimize editor focus
  examples/esbuild.config.mjs
  packages/core/src/shared/common.ts
  packages/docs-ui/src/controllers/text-selection.controller.ts
  packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
Labels: qa:untested

#1590 fix(find-replace): fix dialog issues
  packages/design/src/components/dialog/Dialog.tsx
  packages/design/src/components/dialog/index.module.less
  packages/find-replace/src/controllers/find-replace.controller.ts
  packages/ui/src/views/components/dialog-part/DialogPart.tsx
Labels: qa:verified

#1593 fix(formula): add OR/TEXT/LEN functions
  packages/engine-formula/src/basics/date.ts
  packages/engine-formula/src/basics/object-class-type.ts
  packages/engine-formula/src/engine/ast-node/suffix-node.ts
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
  packages/engine-formula/src/engine/utils/char-kit.ts
  packages/engine-formula/src/engine/value-object/primitive-object.ts
  packages/engine-formula/src/functions/date/date/index.ts
  packages/engine-formula/src/functions/date/edate/index.ts
  packages/engine-formula/src/functions/date/today/index.ts
  packages/engine-formula/src/functions/logical/function-map.ts
  packages/engine-formula/src/functions/logical/or/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/or/index.ts
  packages/engine-formula/src/functions/text/function-map.ts
  packages/engine-formula/src/functions/text/len/__test__/index.spec.ts
  packages/engine-formula/src/functions/text/len/index.ts
  packages/engine-formula/src/functions/text/lenb/__test__/index.spec.ts
  packages/engine-formula/src/functions/text/lenb/index.ts
  packages/engine-formula/src/functions/text/text/__test__/index.spec.ts
  packages/engine-formula/src/functions/text/text/index.ts
  packages/sheets-formula/src/locale/function-list/logical/en-US.ts
  packages/sheets-formula/src/locale/function-list/logical/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/logical/zh-CN.ts
  packages/sheets-formula/src/locale/function-list/text/en-US.ts
  packages/sheets-formula/src/locale/function-list/text/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/text/zh-CN.ts
  packages/sheets-formula/src/services/function-list/logical.ts
  packages/sheets-formula/src/services/function-list/text.ts
Labels: qa:untested

#1520 fix(sheet): fix error edit position after merging
  packages/sheets-ui/src/commands/commands/add-worksheet-merge.command.ts
  packages/sheets/src/commands/utils/handle-merge-operation.ts
  packages/ui/src/services/layout/layout.service.ts
Labels: qa:verified

#1526 fix(sheet): fix the issue of incorrect number of merged cells in the …
  packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
  packages/sheets-ui/src/services/format-painter/format-painter.service.ts
Labels: qa:verified

#1644 fix(formula): array cache error
  packages/engine-formula/src/engine/value-object/array-value-object.ts
  pnpm-lock.yaml
Labels: qa:untested

#1649 fix(editor): control state
  packages/ui/src/components/editor/TextEditor.tsx
  packages/ui/src/services/editor/editor.service.ts
Labels: qa:untested

#1647 fix: rectangle subtract func
  packages/core/src/shared/__test__/rectangle.spec.ts
  packages/core/src/shared/rectangle.ts
  packages/engine-render/src/basics/viewport-subtract.ts
  packages/engine-render/src/viewport.ts
Labels: qa:verified

#1653 fix(slide): image loaded
  packages/engine-render/src/base-object.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/shape/picture.ts
  packages/engine-render/src/thin-scene.ts
  packages/slides/src/views/render/canvas-view.ts
Labels: qa:untested

#1656 fix(sheet): handleRemoveRowsCols util func
  packages/sheets/src/services/ref-range/__tests__/util.spec.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#1574 perf(engine-render): optimize border perf
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/engine-render/src/basics/draw.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/context.ts
Labels: qa:verified

#1665 fix(sheets-ui): merge setRangeValuesMutation at clipboardservice
  packages/sheets-ui/src/index.ts
  packages/sheets-ui/src/services/clipboard/__tests__/utils.spec.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/utils.ts
Labels: qa:verified

#1667 fix: wrong doc example data
  examples/src/data/docs/default-document-data-cn.ts
Labels: qa:verified

#1662 fix(editor): preload the editor
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-ui/src/controllers/editor/editing.controller.ts
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/services/editor/formula-editor-manager.service.ts
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
Labels: qa:verified

#1683 fix(ui): canvas popup event bind error
  packages/design/src/components/popup/RectPopup.tsx
  packages/sheets-ui/src/index.ts
  packages/sheets-ui/src/services/canvas-pop-manager.service.ts
  packages/sheets-ui/src/sheets-ui-plugin.ts
  packages/ui/src/index.ts
  packages/ui/src/services/popup/canvas-popup.service.ts
  packages/ui/src/ui-plugin.ts
  packages/ui/src/views/components/popup/CanvasPopup.tsx
  packages/ui/src/views/components/popup/index.ts
  packages/ui/src/views/parts.ts
Labels: qa:verified

#1691 fix: null-value unexpected deleted by moving
  packages/core/src/shared/__test__/object-matrix.spec.ts
  packages/core/src/shared/object-matrix.ts
Labels: qa:verified

#1661 fix(sheet): fix the selection is incorrect when autofill intersects w…
  packages/sheets-ui/src/services/selection/selection-shape-extension.ts
Labels: qa:verified

#1521 fix(sheet): fix toolbar state when there is overlapping selection
  packages/sheets-ui/src/controllers/menu/merge.menu.ts
  packages/sheets-ui/src/controllers/utils/selections-tools.ts
Labels: qa:verified

#1704 fix(sheet): set-tab-order-mutation should has fromIndex in parmas for transforming
  packages/sheets/src/commands/commands/set-worksheet-order.command.ts
  packages/sheets/src/commands/mutations/set-worksheet-order.mutation.ts
Labels: qa:verified

#1697 fix(render): media change for refresh canvas
  .vscode/settings.json
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/engine.ts
Labels: qa:verified
