Repository dream-num/univer, pull requests merged in 2024-06, with the labels that each got.

#2378 fix(sheets-hyper-link-ui): email link jump error
  packages/sheets-hyper-link-ui/src/common/util.ts
  packages/sheets-hyper-link-ui/src/controllers/copy-paste.controller.ts
  packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts
Labels: qa:verified

#2342 fix(formula): progress for multiple calculation
  packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
  packages/engine-formula/src/engine/value-object/array-value-object.ts
  packages/engine-formula/src/index.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/ui/src/components/progress-bar/ProgressBar.tsx
  packages/ui/src/services/progress/progress.service.ts
Labels: qa:verified

#2318 fix: formular confirm error
  packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
  packages/sheets-ui/src/views/defined-name/DefinedName.tsx
  packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
  packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
  packages/sheets/src/services/selection-manager.service.ts
Labels: qa:verified

#2387 fix(drawing-ui): fix incomplete display of drawing panel styles
  packages/drawing-ui/src/views/panel/DrawingArrange.tsx
  packages/drawing-ui/src/views/panel/DrawingGroup.tsx
  packages/drawing-ui/src/views/panel/ImageCropper.tsx
  packages/drawing-ui/src/views/panel/index.module.less
Labels: qa:verified

#2348 feat: add scrollLeftTop for sheet snapshot
  packages/docs-ui/src/controllers/back-scroll.controller.ts
  packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
  packages/docs-ui/src/controllers/zoom.controller.ts
  packages/engine-render/src/basics/scroll-xy.ts
  packages/engine-render/src/components/sheets/interfaces.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/scene.ts
  packages/engine-render/src/scroll-timer.ts
  packages/engine-render/src/viewport.ts
  packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
  packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
  packages/sheets-ui/src/commands/commands/__tests__/set-frozen.command.spec.ts
  packages/sheets-ui/src/commands/commands/set-frozen.command.ts
  packages/sheets-ui/src/commands/commands/set-scroll.command.ts
  packages/sheets-ui/src/commands/operations/scroll.operation.ts
  packages/sheets-ui/src/common/utils.ts
  packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
  packages/sheets-ui/src/services/drag-manager.service.ts
  packages/sheets-ui/src/services/hover-manager.service.ts
  packages/sheets-ui/src/services/scroll-manager.service.ts
  packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
  packages/slides/src/views/render/adaptors/docs-adaptor.ts
  packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
  packages/slides/src/views/render/canvas-view.ts
Labels: scope:rendering

#2380 fix: sync actions between formula editor and cell editor
  packages/core/src/types/interfaces/i-document-data.ts
  packages/docs/src/commands/commands/core-editing.command.ts
  packages/docs/src/commands/commands/inline-format.command.ts
  packages/docs/src/index.ts
  packages/engine-render/src/components/docs/layout/tools.ts
  packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
  packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
Labels: qa:verified

#2354 fix: not escape when copy content
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
Labels: qa:verified

#2418 feat(sheets-ui): support drawing print
  packages/drawing-ui/src/controllers/image-update.controller.ts
  packages/drawing-ui/src/index.ts
  packages/drawing-ui/src/plugin.ts
  packages/drawing-ui/src/services/drawing-render.service.ts
  packages/engine-render/src/base-object.ts
  packages/engine-render/src/basics/interfaces.ts
  packages/engine-render/src/components/sheets/extensions/marker.ts
  packages/engine-render/src/context.ts
  packages/sheets-data-validation/src/widgets/dropdown-widget.ts
  packages/sheets-drawing-ui/src/controllers/sheet-drawing-printing.controller.ts
  packages/sheets-drawing-ui/src/plugin.ts
  packages/sheets-ui/src/index.ts
  packages/sheets-ui/src/services/print-interceptor.service.ts
  packages/sheets-ui/src/sheets-ui-plugin.ts
Labels: qa:verified

#2371 fix(formula): js precision problem
  packages/core/src/common/request-immediate-macro-task.ts
  packages/engine-formula/src/engine/utils/__tests__/math-kit.spec.ts
  packages/engine-formula/src/engine/utils/math-kit.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-ceil.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-floor.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-minus.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-object.spec.ts
  packages/engine-formula/src/engine/value-object/__tests__/array-value-round.spec.ts
  packages/engine-formula/src/engine/value-object/primitive-object.ts
  packages/engine-formula/src/functions/__tests__/create-function-test-bed.ts
  packages/engine-formula/src/functions/math/mod/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/power/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/subtotal/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/sum/__tests__/index.spec.ts
  packages/engine-formula/src/functions/statistical/stdev-p/__tests__/index.spec.ts
  packages/engine-formula/src/index.ts
  packages/engine-formula/src/services/calculate-formula.service.ts
  packages/sheets-formula/src/controllers/array-formula-display.controller.ts
  packages/sheets-formula/src/controllers/formula-render.controller.ts
  packages/sheets-formula/src/controllers/utils/__tests__/utils.spec.ts
  packages/sheets-formula/src/controllers/utils/utils.ts
Labels: qa:verified

#2436 fix(sheets-data-validation): build error
  packages/engine-render/src/context.ts
Labels: qa:verified

#2412 feat(sheets-data-validation): add validator service allowing developer to get status of data-validation
  packages/data-validation/src/models/data-validation-manager.ts
  packages/data-validation/src/models/data-validation-model.ts
  packages/sheets-data-validation/src/index.ts
  packages/sheets-data-validation/src/models/sheet-data-validation-manager.ts
  packages/sheets-data-validation/src/plugin.ts
  packages/sheets-data-validation/src/services/dv-validator-service.ts
Labels: qa:verified

#2414 feat: add scrollLeftTop for sheet snapshot
  packages/core/src/sheets/worksheet.ts
  packages/docs-ui/src/controllers/back-scroll.controller.ts
  packages/docs-ui/src/controllers/doc-editor-bridge.controller.ts
  packages/docs-ui/src/controllers/zoom.controller.ts
  packages/engine-render/src/basics/scroll-xy.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/scene.ts
  packages/engine-render/src/scroll-timer.ts
  packages/engine-render/src/viewport.ts
  packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
  packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
  packages/sheets-ui/src/commands/commands/__tests__/create-selection-command-test-bed.ts
  packages/sheets-ui/src/commands/commands/__tests__/set-frozen.command.spec.ts
  packages/sheets-ui/src/commands/commands/set-frozen.command.ts
  packages/sheets-ui/src/commands/commands/set-scroll.command.ts
  packages/sheets-ui/src/commands/operations/scroll.operation.ts
  packages/sheets-ui/src/common/keys.ts
  packages/sheets-ui/src/common/utils.ts
  packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/header-move.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/header-resize.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/selection.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
  packages/sheets-ui/src/controllers/utils/component-tools.ts
  packages/sheets-ui/src/index.ts
  packages/sheets-ui/src/services/drag-manager.service.ts
  packages/sheets-ui/src/services/hover-manager.service.ts
  packages/sheets-ui/src/services/scroll-manager.service.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
  packages/sheets-ui/src/services/selection/selection-shape-extension.ts
  packages/sheets-ui/src/services/sheet-skeleton-manager.service.ts
  packages/sheets-ui/src/sheets-ui-plugin.ts
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
  packages/slides/src/views/render/adaptors/docs-adaptor.ts
  packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
  packages/slides/src/views/render/canvas-view.ts
Labels: feature request, scope:rendering, qa:verified, scope:sheets, scope: freeze

#2514 fix: scrollInfo should not save into snapshot
  packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
Labels: qa:verified

#2389 fix(formula): reverse undo range list
  packages/engine-formula/src/models/formula-data.model.ts
  packages/engine-formula/src/models/utils/formula-data-util.ts
  packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-formula/src/controllers/utils/__tests__/ref-range-formula.spec.ts
  packages/sheets-formula/src/controllers/utils/ref-range-formula.ts
Labels: qa:verified

#2485 fix(sheet): button class priority
  packages/sheets-filter-ui/src/views/components/index.module.less
  packages/ui/src/components/range-selector/index.module.less
Labels: qa:verified

#2527 fix(sheets): bugfix for data-validation and hyper-link
  packages/core/src/shared/common.ts
  packages/core/src/types/interfaces/i-cell-data.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-data-validation/src/controllers/dv-render.controller.ts
  packages/sheets-hyper-link-ui/src/common/util.ts
  packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts
Labels: qa:verified

#2448 fix(sheet): force string sets style
  packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts
  packages/sheets/src/commands/mutations/__tests__/set-range-values.mutation.spec.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:verified

#2536 fix(sheets): fix some bugs
  packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
  packages/sheets-ui/src/common/utils.ts
  packages/sheets/src/commands/commands/remove-worksheet-merge.command.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
  packages/ui/src/utils/cell.ts
Labels: qa:verified

#2541 fix: button style
  packages/sheets-filter-ui/src/views/components/index.module.less
  packages/ui/src/components/range-selector/RangeSelector.tsx
  packages/ui/src/components/range-selector/index.module.less
Labels: qa:verified

#2516 fix(sheets-ui): fix unhide render controller RENDER_COMMANDS
  packages/sheets-ui/src/controllers/render-controllers/header-unhide.render-controller.ts
Labels: qa:verified

#2517 fix(sheets): hide rows cols should skip over already hidden ranges
  packages/sheets/src/commands/commands/__tests__/set-row-col-visible.command.spec.ts
  packages/sheets/src/commands/commands/set-col-visible.command.ts
  packages/sheets/src/commands/commands/set-row-visible.command.ts
Labels: qa:verified

#2456 fix: use @univerjs/ui useObservable
  packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.tsx
  packages/sheets-thread-comment/src/views/sheets-thread-comment-panel/index.tsx
  packages/ui/src/views/components/shortcut-panel/ShortcutPanel.tsx
Labels: qa:untested

#2510 fix(design): fix popup position
  packages/design/src/components/popup/RectPopup.tsx
Labels: qa:verified

#2472 feat: everything feels very lag when there is a long range dashrect(cliparea)
  packages/core/src/shared/rectangle.ts
  packages/core/src/types/interfaces/i-range.ts
  packages/engine-render/src/base-object.ts
  packages/engine-render/src/basics/transform.ts
  packages/engine-render/src/basics/vector2.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/group.ts
  packages/engine-render/src/shape/rect.ts
  packages/engine-render/src/shape/shape.ts
  packages/engine-render/src/viewport.ts
  packages/sheets-ui/src/controllers/render-controllers/sheet-render.controller.ts
  packages/sheets-ui/src/services/selection/selection-render-model.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
Labels: qa:verified

#2545 fix(sheets): fix some bugs
  packages/sheets-filter-ui/src/models/__tests__/conditions.spec.ts
  packages/sheets-filter-ui/src/models/conditions.ts
  packages/sheets-filter/src/controllers/sheets-filter.controller.ts
  packages/sheets-ui/src/controllers/auto-fill.controller.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/selection/selection-shape-extension.ts
Labels: qa:verified

#2556 fix(design): adjust tooltip arrow width to 4px
  packages/design/src/components/tooltip/Tooltip.tsx
  packages/design/src/components/tooltip/index.module.less
Labels: qa:untested

#2562 fix(sheets-data-validation): bugfix for data-validation
  packages/design/src/components/tooltip/Tooltip.stories.tsx
  packages/sheets-data-validation/src/controllers/dv-auto-fill.controller.ts
  packages/sheets-data-validation/src/widgets/dropdown-widget.ts
  packages/sheets-hyper-link-ui/src/locale/en-US.ts
  packages/sheets-hyper-link-ui/src/services/popup.service.ts
  packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.module.less
  packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.tsx
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#2557 fix(sheet): selection order
  packages/sheets-ui/src/controllers/render-controllers/selection.render-controller.ts
  packages/sheets/src/services/selection-manager.service.ts
Labels: qa:untested

#2531 fix(formula): remove non-existent formula ids
  packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
  packages/engine-formula/src/functions/lookup/address/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/address/index.ts
  packages/engine-formula/src/functions/lookup/index/index.ts
  packages/engine-formula/src/functions/lookup/offset/index.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/sheets-formula/src/controllers/formula-alert-render.controller.ts
  packages/sheets-formula/src/formula-ui-plugin.ts
  packages/sheets-formula/src/views/prompt/help-function/HelpFunction.tsx
Labels: qa:verified

#2602 fix: icon set dropdown style
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/iconSet.tsx
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.module.less
  packages/ui/src/components/hooks/layout.ts
  packages/ui/src/components/index.ts
Labels: qa:verified

#2544 fix(sheet): duplicate sheet name copy
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/sheets-ui/src/controllers/menu/sheet.menu.ts
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
  packages/sheets/src/commands/commands/__tests__/copy-worksheet.command.spec.ts
  packages/sheets/src/commands/commands/copy-worksheet.command.ts
  packages/sheets/src/locale/en-US.ts
  packages/sheets/src/locale/ru-RU.ts
  packages/sheets/src/locale/zh-CN.ts
Labels: qa:verified

#2609 fix(move-range): add move range controller
  packages/sheets-ui/src/sheets-ui-plugin.ts
Labels: qa:verified

#2607 fix(range-selector): placeholder flush
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
  packages/ui/src/components/editor/TextEditor.tsx
Labels: qa:verified

#2605 fix(conditional-formatting): distinguish between settings and purges …
  packages/sheets-conditional-formatting-ui/src/controllers/cf.auto-fill.controller.ts
Labels: qa:verified

#2601 fix(conditional-formatting): disable clear cf
  packages/sheets-conditional-formatting-ui/src/menu/manage-rule.ts
Labels: qa:verified

#2608 fix(conditional-formatting): reopen panel and update panel
  packages/sheets-conditional-formatting-ui/src/controllers/cf.menu.controller.ts
Labels: qa:verified

#2600 feat(conditional-formatting): add error interceptor
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/formula.tsx
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/highlightCell.tsx
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/index.tsx
  packages/sheets-conditional-formatting-ui/src/components/wrapper-error/WrapperError.tsx
  packages/sheets-conditional-formatting-ui/src/locale/en-US.ts
  packages/sheets-conditional-formatting-ui/src/locale/ru-RU.ts
  packages/sheets-conditional-formatting-ui/src/locale/zh-CN.ts
Labels: qa:verified

#2611 fix(numfmt): reselect item and throw error
  packages/sheets-numfmt/src/components/currency/index.tsx
  packages/sheets-numfmt/src/components/date/index.tsx
  packages/sheets-numfmt/src/components/thousandth-percentile/index.tsx
Labels: qa:verified

#2617 fix(numfmt): numfmt not render after auto fill
  packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
Labels: qa:verified

#2612 fix: fix some paste bugs
  packages/core/src/index.ts
  packages/core/src/types/const/clipboard.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/paste-plugins/plugin-word.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/engine-render/src/index.ts
  packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-form-excel.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
  packages/ui/src/utils/cell.ts
Labels: qa:verified

#2613 feat(formula): add choose function
  packages/engine-formula/src/engine/utils/__tests__/numfmt-kit.spec.ts
  packages/engine-formula/src/engine/utils/numfmt-kit.ts
  packages/engine-formula/src/engine/value-object/primitive-object.ts
  packages/engine-formula/src/functions/__tests__/nested-functions.spec.ts
  packages/engine-formula/src/functions/lookup/choose/__tests__/index.spec.ts
  packages/engine-formula/src/functions/lookup/choose/index.ts
  packages/engine-formula/src/functions/lookup/function-map.ts
  packages/sheets-formula/src/locale/function-list/lookup/en-US.ts
  packages/sheets-formula/src/locale/function-list/lookup/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/lookup/zh-CN.ts
  packages/sheets-formula/src/services/function-list/lookup.ts
Labels: qa:verified
