Repository dream-num/univer, pull requests merged in 2024-02, with the labels that each got.

#1345 fix(sheet-ui): fix clipboard not available in unsecure context
  packages/ui/src/services/clipboard/clipboard-interface.service.ts
  packages/ui/src/services/clipboard/clipboard-utils.ts
Labels: qa:verified

#1305 fix(formula): get rich text data stream as content
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
  packages/engine-formula/src/engine/utils/__tests__/cell.spec.ts
  packages/engine-formula/src/engine/utils/cell.ts
  packages/sheets-formula/src/commands/operations/__tests__/insert-function.operation.spec.ts
  packages/sheets-formula/src/commands/operations/insert-function.operation.ts
Labels: qa:verified

#1330 fix: paste row height and col width
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
Labels: pr:need-auto-tests

#1353 fix: cut paste undo bug & optimize status bar calc
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/controllers/status-bar.controller.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets/src/commands/commands/move-range.command.ts
  packages/sheets/src/commands/commands/utils/selection-utils.ts
Labels: qa:untested

#1359 fix(sheet): formula ref move
  packages/sheets-formula/src/controllers/update-formula.controller.ts
Labels: qa:verified

#1358 fix(sheet): auto add bracket
  packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
  packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
Labels: qa:verified

#1409 fix(sheet): suffix
  packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
  packages/engine-formula/src/engine/analysis/__tests__/lexer.spec.ts
  packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
Labels: qa:verified

#1399 fix(doc): copy data
  packages/docs-ui/src/services/clipboard/udm-to-html/__test__/convertor.spec.ts
  packages/docs-ui/src/services/clipboard/udm-to-html/convertor.ts
Labels: qa:verified

#1360 fix(sheet): formula boolean value
  packages/engine-formula/src/engine/ast-node/value-node.ts
Labels: qa:verified

#1402 fix: page blank screen
  examples/src/data/docs/default-document-data-cn.ts
  packages/engine-render/src/components/docs/block/paragraph/layout-ruler.ts
Labels: qa:verified

#1401 fix: inline menu highlight
  packages/core/src/sheets/__tests__/ranges.spec.ts
  packages/core/src/sheets/range.ts
Labels: qa:verified

#1437 fix(editor): zen error and formula align
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/engine-render/src/layer.ts
  packages/engine-render/src/scene.-transformer.ts
  packages/engine-render/src/shape/base-scroll-bar.ts
  packages/engine-render/src/thin-scene.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
  packages/sheets-zen-editor/src/controllers/zen-editor-ui.controller.ts
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
  packages/ui/src/services/editor/editor.service.ts
Labels: qa:verified
