Repository dream-num/univer, pull requests merged in 2024-08, with the labels that each got.

#2915 fix(conditional-formatting): can not add custom formula
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/formula.tsx
Labels: qa:verified

#2644 feat(formula): add logical functions
  packages/engine-formula/src/functions/logical/false/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/false/index.ts
  packages/engine-formula/src/functions/logical/function-map.ts
  packages/engine-formula/src/functions/logical/ifna/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/ifna/index.ts
  packages/engine-formula/src/functions/logical/ifs/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/ifs/index.ts
  packages/engine-formula/src/functions/logical/not/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/not/index.ts
  packages/engine-formula/src/functions/logical/switch/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/switch/index.ts
  packages/engine-formula/src/functions/logical/true/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/true/index.ts
  packages/engine-formula/src/functions/logical/xor/__tests__/index.spec.ts
  packages/engine-formula/src/functions/logical/xor/index.ts
  packages/sheets-formula/src/locale/function-list/logical/en-US.ts
  packages/sheets-formula/src/locale/function-list/logical/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/logical/zh-CN.ts
  packages/sheets-formula/src/services/function-list/logical.ts
Labels: qa:verified

#2943 fix: context menu disable status
  packages/docs-ui/src/controllers/menu/context-menu.ts
Labels: qa:verified

#2947 fix: fix create lists in table
  packages/docs/src/commands/commands/list.command.ts
Labels: qa:verified

#2949 fix: context menu should not clear selections
  packages/engine-render/src/components/docs/text-selection/convert-rect-range.ts
  packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
Labels: qa:verified

#2953 fix: selection is wrong when select table
  packages/engine-render/src/components/docs/text-selection/selection-utils.ts
Labels: qa:verified

#2954 fix: can not select text when the last page ends with table
  packages/engine-render/src/components/docs/layout/tools.ts
Labels: qa:verified

#2956 fix: can not edit in footer
  packages/engine-render/src/components/docs/layout/doc-skeleton.ts
Labels: qa:verified

#2918 fix: issue #1791
  packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
Labels: qa:verified

#2960 fix: can not insert table in link
  packages/docs-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#2962 fix: disable image when select table
  packages/docs-drawing-ui/src/views/menu/image.menu.ts
  packages/docs-thread-comment-ui/src/controllers/menu.ts
Labels: qa:verified

#2964 fix: insert col right to cursor
  packages/docs/src/commands/commands/table/table.ts
Labels: qa:verified

#2965 fix: add range type when create selection
  packages/docs/src/commands/commands/inline-format.command.ts
  packages/docs/src/commands/mutations/core-editing.mutation.ts
  packages/docs/src/services/text-selection-manager.service.ts
  packages/engine-render/src/basics/range.ts
  packages/engine-render/src/components/docs/text-selection/selection-utils.ts
  packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
Labels: qa:verified

#2967 fix: add table create row col limit to 20
  packages/docs-ui/src/views/table/create/TableCreate.tsx
Labels: qa:verified

#2908 fix(formula): fix formula sheet name uppercase bug
  packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
  packages/sheets-ui/src/controllers/editor/__tests__/mock-function.service.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
  packages/sheets-ui/src/controllers/utils/char-tools.ts
Labels: qa:verified

#2920 fix(formula): fix some bugs
  packages/engine-formula/src/functions/information/iseven/iseven.ts
  packages/engine-formula/src/functions/information/isodd/isodd.ts
  packages/engine-formula/src/functions/lookup/indirect/index.ts
  packages/engine-formula/src/services/runtime.service.ts
  packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
  packages/sheets-formula/src/controllers/array-formula-display.controller.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
Labels: qa:verified

#2983 fix(sheets-ui): set frozen to max column should limited & doc list-paragraph optimize
  packages/docs-ui/src/controllers/doc-auto-format.controller.ts
  packages/docs/src/commands/commands/list.command.ts
  packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
  packages/slides-ui/src/controllers/slide-editing.render-controller.ts
Labels: qa:verified

#2957 fix: modify the judgment logic of rich text
  packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
Labels: qa:verified

#2977 fix: default setting in header and footer
  packages/docs-ui/src/views/header-footer/panel/DocHeaderFooterOptions.tsx
Labels: qa:verified

#2997 fix(paragraph): when switching from 2 lines to 1 line, the selection …
  packages/docs-ui/src/views/paragraph-setting/hook/utils.ts
Labels: qa:verified

#3018 fix(sheets-data-validation): date data validation format not work & optimize popup-service
  packages/core/src/docs/data-model/text-x/apply-utils/update-apply.ts
  packages/data-validation/src/validators/base-data-validator.ts
  packages/docs-hyper-link-ui/src/commands/commands/add-link.command.ts
  packages/docs-hyper-link-ui/src/controllers/doc-hyper-link-clipboard.controller.ts
  packages/docs-ui/src/services/doc-popup-manager.service.ts
  packages/docs/src/basics/replace.ts
  packages/docs/src/commands/commands/clipboard.inner.command.ts
  packages/docs/src/commands/commands/replace-content.command.ts
  packages/sheets-data-validation/src/controllers/dv-reject-input.controller.ts
  packages/sheets-data-validation/src/controllers/dv.controller.ts
  packages/sheets-data-validation/src/index.ts
  packages/sheets-data-validation/src/locale/en-US.ts
  packages/sheets-data-validation/src/locale/ru-RU.ts
  packages/sheets-data-validation/src/locale/vi-VN.ts
  packages/sheets-data-validation/src/locale/zh-CN.ts
  packages/sheets-data-validation/src/locale/zh-TW.ts
  packages/sheets-data-validation/src/mobile-plugin.ts
  packages/sheets-data-validation/src/models/sheet-data-validation-manager.ts
  packages/sheets-data-validation/src/plugin.ts
  packages/sheets-data-validation/src/services/dropdown-manager.service.ts
  packages/sheets-data-validation/src/services/dv-validator-service.ts
  packages/sheets-data-validation/src/services/dv.service.ts
  packages/sheets-data-validation/src/services/dv.tips.ts
  packages/sheets-data-validation/src/validators/date-validator.ts
  packages/sheets-data-validation/src/views/date-dropdown/index.tsx
  packages/sheets-data-validation/src/views/list-dropdown/index.tsx
  packages/sheets-data-validation/src/views/options/index.tsx
  packages/sheets-hyper-link-ui/README.md
  packages/sheets-hyper-link-ui/src/commands/commands/add-hyper-link.command.ts
  packages/sheets-hyper-link-ui/src/commands/commands/remove-hyper-link.command.ts
  packages/sheets-hyper-link-ui/src/commands/commands/update-hyper-link.command.ts
  packages/sheets-hyper-link-ui/src/controllers/popup.controller.ts
  packages/sheets-hyper-link-ui/src/controllers/set-range.controller.ts
  packages/sheets-hyper-link-ui/src/controllers/ui.controller.ts
  packages/sheets-hyper-link-ui/src/index.ts
  packages/sheets-hyper-link-ui/src/views/CellLinkEdit/index.tsx
  packages/sheets-hyper-link-ui/src/views/CellLinkPopup/index.tsx
  packages/sheets-hyper-link/src/controllers/sheet-hyper-link.controller.ts
  packages/sheets-hyper-link/src/index.ts
  packages/sheets-hyper-link/src/types/interfaces/i-hyper-link.ts
  packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
  packages/sheets-thread-comment/README.md
  packages/sheets-thread-comment/src/index.ts
  packages/sheets-thread-comment/src/services/sheets-thread-comment-popup.service.ts
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/services/canvas-pop-manager.service.ts
  packages/sheets-ui/src/services/cell-alert-manager.service.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-paste-from-google.spec.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
  packages/slides-ui/src/services/slide-popup-manager.service.ts
  packages/ui/src/services/popup/canvas-popup.service.ts
  packages/ui/src/views/components/popup/CanvasPopup.tsx
Labels: qa:verified

#3039 fix(sheet): pivot data spill
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
  packages/engine-formula/src/engine/utils/get-runtime-feature-cell.ts
  packages/engine-formula/src/services/runtime.service.ts
Labels: qa:untested

#3081 fix(permission): fix permission bugs 0815
  packages/core/src/services/authz-io/authz-io-local.service.ts
  packages/core/src/services/permission/permission.service.ts
  packages/sheets-ui/src/controllers/permission/sheet-permission-init.controller.ts
  packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
  packages/sheets-ui/src/views/permission/footer/permission-detail-footer.tsx
  packages/sheets/src/model/range-protection-rule.model.ts
  packages/sheets/src/services/permission/range-permission/range-protection.service.ts
  packages/sheets/src/services/permission/worksheet-permission/worksheet-permission-point.model.ts
  packages/sheets/src/services/permission/worksheet-permission/worksheet-permission-rule.model.ts
  packages/sheets/src/services/permission/worksheet-permission/worksheet-permission.service.ts
Labels: qa:verified

#3077 fix(docs): delete paragraph break in table cell
  packages/docs/src/commands/commands/delete.command.ts
  packages/docs/src/commands/commands/table/table.ts
Labels: qa:verified

#3057 feat(sheets-data-validation): support dropdown filter & fix paste error on data-validation cell
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/core/src/types/const/const.ts
  packages/sheets-data-validation/package.json
  packages/sheets-data-validation/src/controllers/dv-render.controller.ts
  packages/sheets-data-validation/src/validators/date-validator.ts
  packages/sheets-data-validation/src/views/list-dropdown/index.tsx
  packages/sheets-data-validation/src/widgets/dropdown-widget.ts
  pnpm-lock.yaml
Labels: qa:verified, scope:data validation

#3060 fix(sheets-ui): watch-range error on move-range
  packages/sheets/src/services/ref-range/ref-range.service.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#3069 fix: update drawing panel state at end of changing
  packages/drawing-ui/src/views/panel/DrawingTransform.tsx
Labels: qa:verified

#3082 fix(docs): line space
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/docs/extensions/line.ts
  packages/engine-render/src/components/docs/text-selection/convert-text-range.ts
Labels: qa:verified

#3041 fix(docs): delete list between tables
  packages/engine-render/src/components/docs/text-selection/selection-utils.ts
Labels: qa:verified

#3064 feat(docs): tab in table
  packages/docs-ui/src/commands/commands/doc-tab.command.ts
  packages/docs-ui/src/controllers/doc-auto-format.controller.ts
  packages/docs-ui/src/docs-ui-plugin.ts
  packages/docs/src/basics/table.ts
  packages/docs/src/commands/commands/auto-format.command.ts
  packages/docs/src/commands/commands/table/doc-table-tab.command.ts
  packages/docs/src/commands/commands/table/table.ts
  packages/docs/src/doc-plugin.ts
  packages/docs/src/index.ts
  packages/docs/src/services/doc-auto-format.service.ts
Labels: qa:verified

#3094 fix(docs): disable some menu items when no selections
  packages/docs-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#3092 fix(docs): no need to scroll to selection when resize page
  packages/docs/src/services/text-selection-manager.service.ts
Labels: qa:verified

#3091 fix(sheets-data-validation): data-validation absolute offset
  packages/engine-formula/src/engine/utils/relative-formula.ts
  packages/engine-formula/src/index.ts
  packages/sheets-data-validation/src/services/dv-custom-formula.service.ts
  packages/sheets-data-validation/src/utils/formula.ts
  packages/sheets-data-validation/src/validators/custom-validator.ts
Labels: qa:verified

#3062 feat(numfmt): currency shortcuts support internationalization
  examples/package.json
  packages-experimental/uni-docs-ui/package.json
  packages-experimental/uni-formula-ui/package.json
  packages-experimental/uni-formula/package.json
  packages-experimental/uni-sheets-ui/package.json
  packages-experimental/uni-slides-ui/package.json
  packages-experimental/uniui/package.json
  packages/design/package.json
  packages/docs-drawing-ui/package.json
  packages/docs-hyper-link-ui/package.json
  packages/docs-thread-comment-ui/package.json
  packages/docs-ui/package.json
  packages/drawing-ui/package.json
  packages/drawing/package.json
  packages/find-replace/package.json
  packages/sheets-conditional-formatting-ui/package.json
  packages/sheets-conditional-formatting/package.json
  packages/sheets-data-validation/package.json
  packages/sheets-drawing-ui/package.json
  packages/sheets-filter-ui/package.json
  packages/sheets-formula/package.json
  packages/sheets-hyper-link-ui/package.json
  packages/sheets-numfmt/package.json
  packages/sheets-numfmt/src/base/const/CURRENCY-SYMBOLS.ts
  packages/sheets-numfmt/src/commands/commands/set-currency.command.ts
  packages/sheets-numfmt/src/controllers/numfmt.menu.controller.ts
  packages/sheets-numfmt/src/index.ts
  packages/sheets-numfmt/src/menu/menu.ts
  packages/sheets-sort-ui/package.json
  packages/sheets-thread-comment/package.json
  packages/sheets-ui/package.json
  packages/sheets-zen-editor/package.json
  packages/slides-ui/package.json
  packages/thread-comment-ui/package.json
  packages/ui/package.json
  packages/ui/src/common/component-manager.ts
  pnpm-lock.yaml
Labels: qa:verified

#3101 fix(docs): line space between image and line
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/docs/extensions/line.ts
  packages/engine-render/src/components/docs/layout/block/paragraph/layout-ruler.ts
  packages/engine-render/src/components/docs/liquid.ts
  packages/engine-render/src/components/docs/text-selection/convert-text-range.ts
Labels: qa:verified

#3102 fix(sheets-data-validation): date validator error when errorStyle=STOP was set
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/data-validation/src/models/data-validation-manager.ts
  packages/data-validation/src/models/data-validation-model.ts
  packages/data-validation/src/validators/base-data-validator.ts
  packages/sheets-data-validation/src/controllers/dv-reject-input.controller.ts
  packages/sheets-data-validation/src/controllers/dv-render.controller.ts
  packages/sheets-data-validation/src/models/sheet-data-validation-manager.ts
  packages/sheets-data-validation/src/services/dv-cache.service.ts
  packages/sheets-data-validation/src/services/dv-validator-service.ts
  packages/sheets-data-validation/src/utils/date.ts
  packages/sheets-data-validation/src/validators/date-validator.ts
  packages/sheets-data-validation/src/views/date-dropdown/index.tsx
  packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/sheet-interceptor/interceptor-const.ts
Labels: qa:verified

#3143 fix(docs): find cursor by coods
  packages/engine-render/src/components/docs/layout/doc-skeleton.ts
  packages/sheets-ui/src/services/editor/cell-editor-manager.service.ts
Labels: qa:verified

#3140 feat(formula): add rank/rank.avg/rank.eq function
  packages/engine-formula/src/functions/compatibility/function-map.ts
  packages/engine-formula/src/functions/compatibility/rank/__tests__/index.spec.ts
  packages/engine-formula/src/functions/compatibility/rank/index.ts
  packages/engine-formula/src/functions/lookup/index/index.ts
  packages/engine-formula/src/functions/lookup/offset/index.ts
  packages/engine-formula/src/functions/statistical/averageif/index.ts
  packages/engine-formula/src/functions/statistical/function-map.ts
  packages/engine-formula/src/functions/statistical/rank-avg/__tests__/index.spec.ts
  packages/engine-formula/src/functions/statistical/rank-avg/index.ts
  packages/engine-formula/src/functions/statistical/rank-eq/__tests__/index.spec.ts
  packages/engine-formula/src/functions/statistical/rank-eq/index.ts
  packages/sheets-formula/src/locale/function-list/compatibility/en-US.ts
  packages/sheets-formula/src/locale/function-list/compatibility/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/compatibility/vi-VN.ts
  packages/sheets-formula/src/locale/function-list/compatibility/zh-CN.ts
  packages/sheets-formula/src/locale/function-list/compatibility/zh-TW.ts
  packages/sheets-formula/src/locale/function-list/statistical/en-US.ts
  packages/sheets-formula/src/locale/function-list/statistical/ja-JP.ts
  packages/sheets-formula/src/locale/function-list/statistical/vi-VN.ts
  packages/sheets-formula/src/locale/function-list/statistical/zh-CN.ts
  packages/sheets-formula/src/locale/function-list/statistical/zh-TW.ts
  packages/sheets-formula/src/services/function-list/compatibility.ts
  packages/sheets-formula/src/services/function-list/statistical.ts
Labels: qa:verified

#3152 fix(sheets-drawing-ui): float-dom-layer position not correct on sheets and uni mode
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages-experimental/uniui/src/controllers/uniui-desktop.controller.tsx
  packages-experimental/uniui/src/views/workbench/UniWorkbench.tsx
  packages/sheets-drawing-ui/src/services/canvas-float-dom-manager.service.ts
  packages/ui/src/services/dom/canvas-dom-layer.service.ts
  packages/ui/src/services/parts/parts.service.ts
  packages/ui/src/views/components/dom/FloatDom.tsx
Labels: qa:verified

#3107 fix(docs-ui): link & checklist can't work on header-footer
  packages-experimental/uni-formula-ui/src/controllers/doc-formula-input.controller.ts
  packages/core/src/docs/data-model/document-data-model.ts
  packages/docs-hyper-link-ui/src/commands/commands/delete-link.command.ts
  packages/docs-hyper-link-ui/src/commands/commands/update-link.command.ts
  packages/docs-hyper-link-ui/src/commands/operations/popup.operation.ts
  packages/docs-hyper-link-ui/src/controllers/doc-hyper-link-selection.controller.ts
  packages/docs-hyper-link-ui/src/controllers/render-controllers/hyper-link-event.render-controller.ts
  packages/docs-hyper-link-ui/src/controllers/ui.controller.ts
  packages/docs-hyper-link-ui/src/locale/en-US.ts
  packages/docs-hyper-link-ui/src/locale/ru-RU.ts
  packages/docs-hyper-link-ui/src/locale/vi-VN.ts
  packages/docs-hyper-link-ui/src/locale/zh-CN.ts
  packages/docs-hyper-link-ui/src/locale/zh-TW.ts
  packages/docs-hyper-link-ui/src/plugin.ts
  packages/docs-hyper-link-ui/src/services/hyper-link-popup.service.ts
  packages/docs-hyper-link-ui/src/views/hyper-link-edit/index.module.less
  packages/docs-hyper-link-ui/src/views/hyper-link-edit/index.tsx
  packages/docs-hyper-link-ui/src/views/hyper-link-popup/index.module.less
  packages/docs-hyper-link-ui/src/views/hyper-link-popup/index.tsx
  packages/docs-thread-comment-ui/src/commands/operations/show-comment-panel.operation.ts
  packages/docs-ui/src/controllers/render-controllers/doc-checklist.render-controller.ts
  packages/docs-ui/src/controllers/render-controllers/doc-hover.render-controller.ts
  packages/docs-ui/src/controllers/render-controllers/doc-resize.render-controller.ts
  packages/docs-ui/src/docs-ui-plugin.ts
  packages/docs-ui/src/index.ts
  packages/docs-ui/src/services/doc-event-manager.service.ts
  packages/docs-ui/src/services/doc-hover-manager.service.ts
  packages/docs-ui/src/services/doc-popup-manager.service.ts
  packages/docs/src/basics/custom-range-factory.ts
  packages/docs/src/basics/custom-range.ts
  packages/docs/src/basics/plain-text.ts
  packages/docs/src/basics/replace.ts
  packages/docs/src/basics/selection.ts
  packages/docs/src/commands/commands/clipboard.inner.command.ts
  packages/docs/src/commands/commands/ime-input.command.ts
  packages/docs/src/commands/commands/list.command.ts
  packages/docs/src/commands/mutations/core-editing.mutation.ts
  packages/docs/src/index.ts
  packages/docs/src/services/doc-auto-format.service.ts
  packages/docs/src/services/doc-interceptor/doc-interceptor.service.ts
  packages/engine-render/src/components/docs/layout/doc-skeleton.ts
  packages/engine-render/src/components/docs/view-model/document-view-model.ts
  packages/thread-comment-ui/src/views/thread-comment-editor/index.tsx
  packages/ui/src/services/popup/canvas-popup.service.ts
  packages/ui/src/views/components/popup/CanvasPopup.tsx
Labels: qa:verified

#3096 fix(docs-ui): limit list maxLevel to 3 when in table & set line-through style on checklist
  packages/core/src/docs/data-model/document-data-model.ts
  packages/core/src/docs/data-model/preset-list-type.ts
  packages/core/src/types/interfaces/i-document-data.ts
  packages/docs/src/basics/paragraph.ts
  packages/docs/src/commands/commands/list.command.ts
  packages/docs/src/index.ts
  packages/engine-render/src/components/docs/layout/block/paragraph/language-ruler.ts
  packages/engine-render/src/components/docs/layout/block/paragraph/shaping.ts
  packages/engine-render/src/components/docs/layout/tools.ts
Labels: qa:verified

#3135 fix: hyper-link ref-range error on filter
  packages/design/src/components/popup/index.module.less
  packages/sheets-hyper-link/src/controllers/ref-range.controller.ts
  packages/sheets-thread-comment-base/src/controllers/sheets-thread-comment-ref-range.controller.ts
  packages/sheets/src/commands/commands/remove-row-col.command.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/ref-range/__tests__/utils.spec.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#3114 fix(formula): skip tree after add to formula run list
  packages/core/src/services/snapshot/snapshot-transform.ts
  packages/engine-formula/src/engine/dependency/formula-dependency.ts
Labels: qa:verified

#3104 fix: ref selection expand after bottom line is over top line, and ref selection fill area(primary cell) and formula editor should clear when change sheet.
  packages/core/src/sheets/worksheet.ts
  packages/drawing-ui/src/controllers/image-cropper.controller.ts
  packages/drawing-ui/src/views/crop/image-cropper-object.ts
  packages/engine-render/src/base-object.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/engine.ts
  packages/engine-render/src/scene.ts
  packages/engine-render/src/shape/rich-text.ts
  packages/engine-render/src/viewport.ts
  packages/sheets-data-validation/src/widgets/dropdown-widget.ts
  packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
  packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/scroll.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/zoom.render-controller.ts
  packages/sheets-ui/src/services/selection/base-selection-render.service.ts
  packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
  packages/sheets-ui/src/services/selection/mobile-selection-shape.ts
  packages/sheets-ui/src/services/selection/selection-render-model.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
  packages/sheets-ui/src/services/selection/selection-shape-extension.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
  packages/sheets-ui/src/views/header-resize-shape.ts
  packages/sheets/src/basics/selection.ts
  packages/sheets/src/services/selections/selection-manager.service.ts
  packages/slides-ui/src/controllers/slide-editing.render-controller.ts
  packages/slides-ui/src/controllers/slide-editor-bridge.render-controller.ts
  packages/slides-ui/src/controllers/slide.render-controller.ts
  packages/slides-ui/src/services/slide-editor-bridge.service.ts
Labels: qa:verified

#3119 fix(sheets-ui): data-validation dropdown hidden when selection change
  packages/sheets-data-validation/src/services/dropdown-manager.service.ts
  packages/sheets-data-validation/src/services/dv-validator-service.ts
  packages/sheets-thread-comment/src/controllers/sheets-thread-comment.controller.ts
Labels: qa:verified

#3174 fix(formula): parser error
  packages/engine-formula/src/basics/error-type.ts
  packages/engine-formula/src/engine/analysis/__tests__/lexer-tree-builder.spec.ts
  packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
  packages/engine-formula/src/engine/analysis/lexer-tree-builder.ts
  packages/engine-formula/src/engine/ast-node/ast-root-node.ts
  packages/engine-formula/src/engine/ast-node/value-node.ts
  packages/engine-formula/src/engine/utils/reference.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-formula/src/services/description.service.ts
Labels: qa:verified

#3170 fix(docs): selection error in table and paragraph
  packages/engine-render/src/components/docs/layout/doc-skeleton.ts
  packages/engine-render/src/components/docs/text-selection/convert-rect-range.ts
  packages/engine-render/src/components/docs/text-selection/convert-text-range.ts
  packages/engine-render/src/components/docs/text-selection/selection-utils.ts
  packages/engine-render/src/components/docs/text-selection/text-selection-render-manager.ts
Labels: qa:verified

#3139 fix: underline not work when align bottom & moving clipboard controller from steady to render
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/extensions/sheet-extension.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/engine-render/src/engine.ts
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/services/editor-bridge.service.ts
  packages/sheets-ui/src/views/editor-container/index.module.less
Labels: qa:verified

#3178 fix: modify the rich text judgment logic
  packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
Labels: qa:verified

#3188 fix(numfmt): numfmt skip null or undefined
  packages/sheets-numfmt/src/controllers/numfmt.cell-content.controller.ts
Labels: qa:verified

#3187 feat(sheet): performan the expand range
  packages/sheets/src/basics/__tests__/expand.data.ts
  packages/sheets/src/basics/__tests__/expand.spec.ts
  packages/sheets/src/basics/expand-range.ts
  packages/sheets/src/index.ts
Labels: qa:verified

#3198 fix(docs): remove content and insert drawing
  packages/docs-drawing-ui/src/commands/commands/insert-doc-drawing.command.ts
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
  packages/docs/src/commands/commands/clipboard.inner.command.ts
  packages/docs/src/index.ts
Labels: qa:verified

#3190 fix(numfmt): support edit percent with numfmt
  packages/core/src/shared/numfmt.ts
  packages/core/src/shared/types/numfmt.type.ts
  packages/engine-formula/src/basics/date.ts
  packages/engine-formula/src/functions/date/datevalue/index.ts
  packages/engine-formula/src/functions/date/timevalue/index.ts
  packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
Labels: qa:verified

#3195 fix(numfmt): add or substract decimal inheritance
  packages/sheets-numfmt/src/commands/commands/add-decimal.command.ts
  packages/sheets-numfmt/src/commands/commands/subtract-decimal.command.ts
Labels: qa:verified

#3204 fix(editor): boolean values do not need to be processed
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
Labels: qa:verified

#3205 fix: sheet dispose cause scroll update scene size failed.
  packages/engine-render/src/render-manager/render-manager.service.ts
  packages/ui/src/controllers/ui/ui-desktop.controller.tsx
Labels: qa:verified

#3207 fix(sheets): do not copy cell bg color to rich text bg
  packages/sheets/src/basics/cell-style.ts
  packages/sheets/src/commands/mutations/set-range-values.mutation.ts
Labels: qa:verified

#3193 fix(sheet): insert wrong columns when shift right
  packages/core/src/shared/types.ts
  packages/sheets-ui/src/controllers/menu/menu-util.ts
  packages/sheets-ui/src/controllers/permission/sheet-permission-interceptor-base.controller.ts
  packages/sheets/src/services/selections/selection-manager.service.ts
Labels: bug:should be fixed

#3214 fix(docs): paste table after table
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
Labels: qa:verified

#3234 fix(docs): copy table only has one row and col
  packages/engine-render/src/components/docs/text-selection/convert-rect-range.ts
Labels: qa:verified

#3196 fix(sheets-sort): wrong order colIndex
  packages/sheets-sort-ui/src/services/sheets-sort-ui.service.tsx
Labels: qa:verified

#3233 fix(docs): show font family after copy from header
  packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
Labels: qa:verified

#3225 fix(docs): reserve the first remove text run
  packages/core/src/docs/data-model/text-x/apply-utils/common.ts
Labels: qa:verified

#3222 fix(docs): no need to scroll when enter zen mode
  packages/engine-render/src/viewport.ts
  packages/sheets-zen-editor/package.json
  packages/sheets-zen-editor/src/commands/commands/zen-editor.command.ts
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
  pnpm-lock.yaml
Labels: qa:verified

#3227 fix(docs): copy paste image form univer doc to univer doc
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
  packages/docs/src/commands/commands/clipboard.inner.command.ts
Labels: qa:verified

#3232 fix(docs): wrong font family in menu
  packages/docs-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#3231 fix(sheets): no style in blank cell
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
Labels: qa:verified

#3071 fix(docs): paste content to univer
  packages/docs-ui/src/services/clipboard/html-to-udm/parse-node-style.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/parse-node-style.ts
Labels: qa:verified

#2993 fix: copy paste between sheet and doc
  packages/docs-ui/src/commands/commands/clipboard.command.ts
  packages/docs-ui/src/controllers/clipboard.controller.ts
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
  packages/docs-ui/src/services/clipboard/html-to-udm/converter.ts
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/views/editor-container/EditorContainer.tsx
  packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
Labels: qa:verified

#3189 fix: sheet text
  packages/drawing-ui/src/controllers/image-cropper.controller.ts
  packages/engine-render/src/components/sheets/column-header.ts
  packages/engine-render/src/components/sheets/extensions/column-header-layout.ts
  packages/engine-render/src/group.ts
  packages/engine-render/src/layer.ts
  packages/engine-render/src/scene.ts
  packages/engine-render/src/shape/shape.ts
  packages/engine-render/src/viewport.ts
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-list/index.tsx
  packages/sheets-drawing-ui/src/controllers/drawing-popup-menu.controller.ts
  packages/sheets-drawing-ui/src/controllers/sheet-drawing-permission.controller.ts
  packages/sheets-filter-ui/src/views/render-modules/sheets-filter.render-controller.ts
  packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
  packages/sheets-formula/src/services/render-services/ref-selections.render-service.ts
  packages/sheets-ui/src/index.ts
  packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
  packages/sheets-ui/src/services/selection/base-selection-render.service.ts
  packages/sheets-ui/src/services/selection/const.ts
  packages/sheets-ui/src/services/selection/mobile-selection-render.service.ts
  packages/sheets-ui/src/services/selection/mobile-selection-shape.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
  packages/sheets-ui/src/services/selection/util.ts
  packages/sheets-ui/src/views/editor-container/index.module.less
Labels: qa:verified

#3208 fix: add rows by paste should support undo
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
Labels: qa:verified

#3230 fix(sheets-drawing): drawing snapshot error
  packages/sheets-drawing-ui/src/controllers/render-controllers/sheet-drawing.render-controller.ts
  packages/sheets-drawing-ui/src/controllers/sheet-drawing-update.controller.ts
  packages/sheets-drawing/src/controllers/sheet-drawing.controller.ts
Labels: qa:verified

#3237 fix(sheets-data-validation): date picker can't input by type when errorStyle is STOP
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/core/src/types/const/const.ts
  packages/sheets-data-validation/src/controllers/dv-reject-input.controller.ts
  packages/sheets-data-validation/src/validators/date-validator.ts
  packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
Labels: qa:verified

#3218 fix(sheets): ref-range watch-range on insert-move-down & insert-move-right
  packages/sheets-thread-comment/src/controllers/sheets-thread-comment.controller.ts
  packages/sheets/src/services/ref-range/util.ts
  packages/sheets/src/services/selections/selection-manager.service.ts
Labels: qa:verified

#3229 fix(conditional-formatting): setting highlight error can not be confi…
  packages/sheets-conditional-formatting-ui/src/components/panel/rule-edit/highlightCell.tsx
Labels: qa:verified

#3215 fix: paste should clear style when paste to editor in sheet
  packages/docs-ui/src/services/clipboard/clipboard.service.ts
Labels: qa:verified

#3247 fix(sheet): make dirty when only local false
  packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
Labels: qa:untested

#3244 fix(formula): fix operation accuracy
  packages/engine-formula/src/engine/utils/math-kit.ts
  packages/engine-formula/src/functions/math/cot/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/coth/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/csch/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/sec/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/sech/__tests__/index.spec.ts
  packages/engine-formula/src/functions/math/subtotal/__tests__/index.spec.ts
  packages/engine-formula/src/functions/statistical/avedev/__tests__/index.spec.ts
  packages/engine-formula/src/functions/statistical/averagea/__tests__/index.spec.ts
Labels: qa:verified

#3228 fix(conditional-formatting): hidden values do not take effect when us…
  packages/sheets-data-validation/src/controllers/dv-render.controller.ts
Labels: qa:verified

#3199 fix(sheets-filter): some filter bugs
  packages/sheets-filter/src/controllers/__tests__/sheets-filter.controller.spec.ts
  packages/sheets-filter/src/controllers/sheets-filter.controller.ts
  packages/sheets/src/services/permission/workbook-permission/util.ts
Labels: qa:verified

#3245 fix: drawing issues
  packages/drawing-ui/src/services/drawing-render.service.ts
  packages/drawing/src/services/drawing-manager-impl.service.ts
  packages/sheets-drawing-ui/src/controllers/sheet-drawing-copy-paste.controller.ts
  packages/sheets-drawing-ui/src/controllers/sheet-drawing-transform-affected.controller.ts
Labels: qa:verified

#3176 feat(docs): support change space rule type
  packages/core/src/types/interfaces/i-document-data.ts
  packages/docs-ui/src/commands/commands/doc-paragraph-setting.command.ts
  packages/docs-ui/src/controllers/doc-paragraph-setting.controller.ts
  packages/docs-ui/src/locale/en-US.ts
  packages/docs-ui/src/locale/ru-RU.ts
  packages/docs-ui/src/locale/vi-VN.ts
  packages/docs-ui/src/locale/zh-CN.ts
  packages/docs-ui/src/locale/zh-TW.ts
  packages/docs-ui/src/views/paragraph-setting/Setting.tsx
  packages/docs-ui/src/views/paragraph-setting/hook/utils.ts
  packages/docs-ui/src/views/paragraph-setting/index.module.less
  packages/docs/src/index.ts
Labels: qa:verified

#3257 fix(formula): fix formula paste
  packages/sheets-formula/src/controllers/__tests__/formula-clipboard.controller.spec.ts
  packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
Labels: qa:verified
