Repository dream-num/univer, pull requests merged in 2024-01, with the labels that each got.

#849 fix(sheet): copypaste & auto filling bugs
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-service.spec.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx
  packages/ui/src/utils/cell.ts
Labels: qa:verified

#950 fix(sheets): fix move row col undo params
  packages/core/src/shared/rectangle.ts
  packages/sheets/src/commands/mutations/__tests__/move-rows-cols.mutation.spec.ts
  packages/sheets/src/commands/mutations/move-rows-cols.mutation.ts
Labels: qa:verified

#955 fix(numfmt): #852 the format is not preserved after the formula is entered
  packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
  packages/sheets-numfmt/src/menu/menu.ts
Labels: qa:verified

#949 fix(numfmt): #853 the cell number format is not consistent with the t…
  packages/sheets-numfmt/src/controllers/numfmt.controller.ts
  packages/sheets-numfmt/src/menu/menu.ts
Labels: qa:verified

#957 fix(sheet): move row remove undefined
  packages/core/src/shared/__test__/object-matrix.spec.ts
  packages/core/src/shared/object-matrix.ts
Labels: qa:verified

#969 fix(sheet): row and column resize
  packages/sheets-ui/src/controllers/header-resize.controller.ts
Labels: qa:untested

#959 fix: padding top issue
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
Labels: qa:verified

#910 fix: inline format in cell
  packages/core/src/docs/data-model/apply-utils/update-apply.ts
  packages/core/src/docs/data-model/document-data-model.ts
  packages/core/src/index.ts
  packages/core/src/shared/common.ts
  packages/core/src/types/interfaces/i-style-data.ts
  packages/docs/src/commands/commands/inline-format.command.ts
  packages/docs/src/controllers/clipboard.controller.ts
  packages/engine-render/src/basics/font-cache.ts
  packages/engine-render/src/components/docs/extensions/line.ts
  packages/sheets-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#922 fix(sheet): freeze bugfix
  packages/sheets-ui/src/commands/commands/__tests__/set-frozen.command.spec.ts
  packages/sheets-ui/src/commands/commands/set-frozen.command.ts
  packages/sheets-ui/src/commands/commands/set-scroll.command.ts
  packages/sheets-ui/src/commands/commands/set-selection-frozen.command.ts
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/controllers/header-move.controller.ts
  packages/sheets-ui/src/controllers/scroll.controller.ts
  packages/sheets-ui/src/controllers/selection.controller.ts
Labels: qa:verified

#979 fix: #911 using the undo shortcut after you clear the content goes into edit mode
  examples/src/plugins/local-save/controller/record.controller.ts
  packages/sheets-numfmt/src/components/more-numfmt-type/MoreNumfmtType.tsx
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
  packages/ui/src/views/components/context-menu/ContextMenu.tsx
  packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
Labels: qa:verified

#984 fix(sheet): resize window viewport error
  packages/engine-render/src/viewport.ts
Labels: qa:verified

#965 fix(sheet): some bugs on copy&past and autofill
  packages/core/src/shared/object-matrix.ts
  packages/engine-render/src/base-object.ts
  packages/engine-render/src/layer.ts
  packages/sheets-formula/src/controllers/active-dirty.controller.ts
  packages/sheets-formula/src/controllers/formula-clipboard.controller.ts
  packages/sheets-numfmt/src/controllers/numfmt.copy-paste.controller.ts
  packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
  packages/sheets-ui/src/commands/commands/auto-fill.command.ts
  packages/sheets-ui/src/controllers/auto-fill.controller.ts
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
  packages/sheets-ui/src/controllers/mark-selection.controller.ts
  packages/sheets-ui/src/controllers/status-bar.controller.ts
  packages/sheets-ui/src/services/auto-fill/tools.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/type.ts
  packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
  packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
  packages/sheets/src/commands/commands/move-range.command.ts
  packages/sheets/src/commands/mutations/move-range.mutation.ts
Labels: qa:verified

#999 fix(render): horizon scroll bar
  packages/docs/src/views/doc-canvas-view.ts
  packages/engine-render/src/scene.ts
  packages/engine-render/src/shape/scroll-bar.ts
  packages/engine-render/src/thin-scene.ts
  packages/engine-render/src/viewport.ts
  packages/sheets-ui/src/views/sheet-canvas-view.ts
  packages/slides/src/views/render/adaptors/docs-adaptor.ts
  packages/slides/src/views/render/adaptors/spreadsheet-adaptor.ts
  packages/slides/src/views/render/canvas-view.ts
Labels: qa:verified

#988 fix(sheet): freeze select selection issues
  packages/engine-render/src/scroll-timer.ts
  packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/controllers/selection.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
Labels: scope:sheets-ui, qa:verified

#915 fix: fx editor cursor
  packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
  packages/sheets-ui/src/services/editor/formula-editor-manager.service.ts
  packages/sheets-ui/src/views/formula-bar/FormulaBar.tsx
Labels: qa:verified

#993 fix(sheet): add disabled status on toolbar menu items
  packages/sheets-formula/src/controllers/menu.ts
  packages/sheets-numfmt/src/menu/menu.ts
  packages/sheets-ui/src/components/font-size/FontSize.tsx
  packages/sheets-ui/src/components/font-size/interface.ts
  packages/sheets-ui/src/controllers/menu/border.menu.ts
  packages/sheets-ui/src/controllers/menu/menu.ts
  packages/sheets-ui/src/controllers/menu/merge.menu.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/permission/index.ts
  packages/sheets/src/services/permission/tool.ts
  packages/ui/src/controllers/shortcut-display/menu.ts
  packages/ui/src/services/menu/menu.ts
  packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
  packages/ui/src/views/components/doc-bars/index.module.less
  packages/uniscript/src/controllers/menu.ts
Labels: qa:verified

#994 fix(sheet): text align in sheet cell
  packages/engine-render/src/components/sheets/extensions/font.ts
Labels: qa:verified

#1007 fix(sheet): formula input
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
Labels: qa:verified

#1002 fix(formula): insert function bug
  packages/sheets-formula/src/commands/operations/__tests__/insert-function.operation.spec.ts
  packages/sheets-formula/src/commands/operations/insert-function.operation.ts
Labels: qa:verified

#1010 fix(sheet): moving col or row relative to freeze area may cause wrong freeze size
  packages/sheets-ui/src/controllers/freeze.controller.ts
Labels: qa:verified

#1031 fix(sheet): #1030 undo failed to restore col-row width
  packages/core/src/shared/object-matrix.ts
  packages/sheets/src/commands/mutations/__tests__/create-command-test-bed.ts
  packages/sheets/src/commands/mutations/__tests__/remove-row-col.mutation.spec.ts
  packages/sheets/src/commands/mutations/remove-row-col.mutation.ts
Labels: qa:verified

#1013 fix(sheet): overflow
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
Labels: qa:verified

#1022 fix(sheets): editing input canvas wrong position when set freeze
  packages/sheets-ui/src/controllers/selection.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
Labels: qa:verified

#1036 fix(nunfmt): #1034 Error moving multiple data formats
  packages/sheets-numfmt/src/__tests__/utils.test.ts
  packages/sheets-numfmt/src/utils/mutation.ts
Labels: qa:verified

#1006 fix(sheet): some bugs on copy&paste
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-formula/src/commands/operations/insert-function.operation.ts
  packages/sheets-ui/package.json
  packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
  packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
  packages/sheets-ui/src/commands/commands/set-selection.command.ts
  packages/sheets-ui/src/controllers/auto-fill.controller.ts
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/controllers/format-painter/format-painter.controller.ts
  packages/sheets-ui/src/controllers/mark-selection.controller.ts
  packages/sheets-ui/src/controllers/status-bar.controller.ts
  packages/sheets-ui/src/services/auto-fill/rules.ts
  packages/sheets-ui/src/services/auto-fill/tools.ts
  packages/sheets-ui/src/services/clipboard/__tests__/clipboard-test-bed.ts
  packages/sheets-ui/src/services/format-painter/format-painter.service.ts
  packages/sheets-ui/src/services/mark-selection/mark-selection.service.ts
  packages/sheets-ui/src/services/status-bar.service.ts
  packages/sheets-ui/src/views/status-bar/CopyableStatisticItem.tsx
  packages/sheets-ui/src/views/status-bar/StatusBar.tsx
  packages/sheets-ui/src/views/status-bar/index.module.less
  packages/sheets/src/commands/commands/__tests__/move-range-commands.spec.ts
  packages/sheets/src/commands/commands/move-range.command.ts
  pnpm-lock.yaml
Labels: qa:verified

#1044 fix(sheet): update for change
  packages/sheets-ui/src/controllers/selection.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
Labels: qa:verified

#1035 fix(formula): redo delete sheet
  packages/engine-formula/src/basics/common.ts
  packages/engine-formula/src/basics/runtime.ts
  packages/engine-formula/src/engine/dependency/formula-dependency.ts
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
  packages/engine-formula/src/engine/reference-object/range-reference-object.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/engine-formula/src/services/calculate-formula.service.ts
  packages/engine-formula/src/services/current-data.service.ts
  packages/engine-formula/src/services/other-formula-manager.service.ts
  packages/engine-formula/src/services/runtime.service.ts
  packages/sheets-formula/src/controllers/active-dirty.controller.ts
  packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-formula/src/controllers/utils.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
  packages/sheets/src/controllers/calculate-result-apply.controller.ts
Labels: qa:verified

#1015 fix: render error after scale
  packages/engine-render/src/components/docs/document.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
Labels: qa:verified

#1046 fix(sheet): auto-fill conflict with freeze
  packages/engine-render/src/scroll-timer.ts
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/controllers/header-move.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
  packages/sheets-ui/src/services/selection/selection-shape-extension.ts
  packages/sheets/src/commands/mutations/set-frozen.mutation.ts
Labels: qa:verified

#1050 fix(sheet): add actualRow and actualColumn to auto fill section
  packages/sheets-ui/src/controllers/auto-fill.controller.ts
  packages/sheets/src/commands/operations/selection.operation.ts
Labels: qa:verified

#1032 fix(sheet): array formula exceed
  packages/engine-formula/src/engine/analysis/__tests__/lexer.spec.ts
  packages/engine-formula/src/engine/dependency/dependency-tree.ts
  packages/engine-formula/src/engine/dependency/formula-dependency.ts
  packages/engine-formula/src/functions/lookup/indirect/__test__/index.spec.ts
  packages/engine-formula/src/functions/math/sum/index.ts
  packages/engine-formula/src/services/calculate-formula.service.ts
  packages/engine-formula/src/services/runtime.service.ts
Labels: qa:verified

#1055 fix: paste line break \n will cause crash
  packages/engine-formula/src/engine/analysis/__tests__/parser.spec.ts
  packages/sheets-ui/src/controllers/clipboard/clipboard.controller.ts
  packages/sheets-ui/src/controllers/clipboard/utils.ts
  packages/sheets-ui/src/services/clipboard/html-to-usm/converter.ts
  packages/sheets-ui/src/services/clipboard/usm-to-html/convertor.ts
Labels: qa:verified

#1052 fix: refresh cell size after edit by zen editor
  packages/sheets-ui/src/controllers/editor-bridge.controller.ts
  packages/sheets-ui/src/services/editor-bridge.service.ts
Labels: qa:verified

#1060 fix: word unnecessary wrap
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
Labels: qa:verified

#1063 fix: wrong content height calculation
  packages/engine-render/src/components/docs/block/paragraph/layout-ruler.ts
Labels: qa:verified

#1075 fix: while rendering cell content, sometimes the text is truncated
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
Labels: qa:verified

#1071 fix(sheet): freeze render error on initialize phase
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/common/keys.ts
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
Labels: qa:verified

#1074 fix(sheet): #1016 drag rows and columns to merge cells in the wrong position
  docs/tldr/handMoveRowsCols.tldr
  packages/sheets-formula/src/controllers/__tests__/update-formula.controller.spec.ts
  packages/sheets-formula/src/controllers/__tests__/utils.spec.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-formula/src/controllers/utils.ts
  packages/sheets-numfmt/src/controllers/numfmt.ref-range.controller.ts
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/controllers/header-move.controller.ts
  packages/sheets/src/commands/commands/__tests__/move-rows-cols.command.spec.ts
  packages/sheets/src/commands/commands/move-rows-cols.command.ts
  packages/sheets/src/controllers/merge-cell.controller.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/ref-range/__tests__/util.spec.ts
  packages/sheets/src/services/ref-range/ref-range.service.ts
  packages/sheets/src/services/ref-range/type.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#1073 fix(header): fix selected range not changed when clicking menu
  packages/sheets-ui/src/components/menu-item-input/MenuItemInput.tsx
  packages/sheets-ui/src/components/menu-item-input/interface.ts
  packages/sheets-ui/src/controllers/header-menu.controller.ts
  packages/sheets-ui/src/controllers/menu/__tests__/create-menu-test-bed.ts
  packages/sheets-ui/src/controllers/menu/menu.ts
Labels: qa:verified

#1079 fix: show full cell editor
  packages/sheets-ui/src/commands/commands/set-scroll.command.ts
  packages/sheets-ui/src/commands/operations/scroll.operation.ts
  packages/sheets-ui/src/controllers/navigation/navigation.controller.ts
  packages/sheets-ui/src/controllers/scroll.controller.ts
  packages/sheets-ui/src/controllers/selection.controller.ts
Labels: qa:verified

#1096 fix(sheet): use backspace empty cell content
  packages/docs/src/commands/commands/list.command.ts
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
Labels: qa:verified

#1090 fix(sheet): #1039 can not type directly into a cell after dragging a …
  packages/sheets/src/commands/commands/move-range.command.ts
Labels: qa:verified

#1020 fix(formula): remove formula when content clear
  packages/engine-formula/src/models/__tests__/formula-data.model.spec.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/sheets-formula/src/controllers/formula-editor-show.controller.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-ui/src/controllers/editor/__tests__/create-test-bed.ts
  packages/sheets-ui/src/controllers/editor/__tests__/end-edit.controller.spec.ts
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
Labels: qa:verified

#841 fix: need to empty formula bar when press backspace
  packages/sheets-ui/src/commands/operations/activate-cell-edit.operation.ts
  packages/sheets-ui/src/controllers/editor-bridge.controller.ts
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
  packages/sheets-ui/src/controllers/editor/formula-editor.controller.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
  packages/sheets-ui/src/services/editor-bridge.service.ts
  packages/sheets-zen-editor/src/commands/commands/zen-editor.command.ts
  packages/sheets-zen-editor/src/controllers/zen-editor.controller.ts
  packages/sheets/src/commands/commands/clear-selection-content.command.ts
  packages/sheets/src/commands/commands/remove-row-col.command.ts
  packages/sheets/src/commands/mutations/remove-row-col.mutation.ts
Labels: qa:verified

#1104 refactor: reduce the use of calculate and refactor view model manager
  packages/docs/src/commands/commands/__tests__/create-command-test-bed.ts
  packages/docs/src/commands/mutations/core-editing.mutation.ts
  packages/docs/src/controllers/ime-input.controller.ts
  packages/docs/src/services/doc-skeleton-manager.service.ts
  packages/docs/src/services/doc-view-model-manager.service.ts
  packages/docs/src/views/doc-canvas-view.ts
  packages/image/src/controllers/image.load.controller.ts
Labels: debt

#917 fix(sheet): sheet bar menu style
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/core/src/sheets/__tests__/create-core-test-bed.ts
  packages/core/src/sheets/__tests__/workbook.spec.ts
  packages/core/src/sheets/workbook.ts
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-menu/index.module.less
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarItem.tsx
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/index.module.less
  packages/sheets/src/commands/commands/__tests__/create-command-test-bed.ts
  packages/sheets/src/commands/commands/insert-sheet.command.ts
  packages/sheets/src/locale/en-US.ts
  packages/sheets/src/locale/zh-CN.ts
Labels: qa:verified

#1040 fix(formula): offset array formula
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets-formula/src/controllers/utils/__tests__/offset-formula-data.spec.ts
  packages/sheets-formula/src/controllers/utils/__tests__/redo-undo-formula-data.spec.ts
  packages/sheets-formula/src/controllers/utils/offset-formula-data.ts
  packages/sheets-formula/src/controllers/utils/redo-undo-formula-data.ts
  packages/sheets-formula/src/views/prompt/help-function/index.module.less
Labels: qa:verified

#1122 fix: backspace in first paragraph
  packages/docs/src/commands/commands/delete.command.ts
Labels: qa:verified

#1126 feat(ref-range): support formula
  docs/tldr/ref-range-remove-col.tldr
  docs/tldr/ref-range-remove-row.tldr
  docs/tldr/ref-range/delete-range-move.tldr
  docs/tldr/ref-range/insert-range-move.tldr
  docs/tldr/ref-range/insert-rows-cols.tldr
  docs/tldr/ref-range/move-range.tldr
  docs/tldr/ref-range/move-rows-cols.tldr
  docs/tldr/ref-range/remove-rows-cols.tldr
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets/src/services/ref-range/__tests__/util.spec.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:untested

#1140 fix(numfmt): #1132 should keep the style and use real values
  packages/sheets-numfmt/src/controllers/numfmt.editor.controller.ts
Labels: qa:untested

#1110 fix(sheet): only one sheet, disable remove button
  packages/sheets-ui/src/controllers/menu/sheet.menu.ts
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarItem.tsx
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/index.module.less
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
Labels: qa:verified

#1141 fix(sheet): the expected pop-up prompt for dragging a cell to a merge…
  packages/sheets/src/commands/commands/__tests__/move-range-commands.spec.ts
  packages/sheets/src/commands/commands/move-range.command.ts
Labels: qa:verified

#1147 feat(merge-cell): support waring when insert or delete range
  packages/sheets-ui/src/commands/commands/delete-range-move-down-confirm.command.ts
  packages/sheets-ui/src/commands/commands/delete-range-move-left-confirm.command .ts
  packages/sheets-ui/src/commands/commands/insert-range-move-right-confirm.command.ts
  packages/sheets-ui/src/commands/commands/insert-range-move-up-confirm.command.ts
  packages/sheets-ui/src/controllers/menu/delete.menu.ts
  packages/sheets-ui/src/controllers/menu/insert.menu.ts
  packages/sheets-ui/src/controllers/sheet-ui.controller.ts
  packages/sheets-ui/src/locale/en-US.ts
  packages/sheets-ui/src/locale/zh-CN.ts
Labels: qa:verified

#1041 fix(ui): disable tooltip from displaying after opening dropdown
  package.json
  packages/design/package.json
  packages/design/src/components/tooltip/Tooltip.tsx
  packages/design/src/components/tooltip/index.module.less
  packages/docs-ui/package.json
  packages/sheets-find/package.json
  packages/sheets-formula/package.json
  packages/sheets-numfmt/package.json
  packages/sheets-ui/package.json
  packages/sheets-ui/src/views/FormulaBar/formulabar-zh.md
  packages/sheets-ui/src/views/count-bar/CountBar.tsx
  packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx
  packages/slides-ui/package.json
  packages/slides/package.json
  packages/ui/package.json
  packages/ui/src/views/components/doc-bars/ToolbarItem.tsx
  packages/uniscript/package.json
  pnpm-lock.yaml
  vitest.workspace.ts
Labels: qa:verified

#1117 fix(sheet-ui): should not activate selection when clicking on header menu
  packages/design/src/components/popup/Popup.tsx
  packages/sheets-ui/src/controllers/header-menu.controller.ts
  packages/sheets-ui/src/controllers/selection.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
Labels: qa:verified

#1156 fix(sheet): #1130 rows and columns should not be allowed to be dragge…
  examples/src/data/sheets/demo/default-workbook-data-demo.ts
  packages/sheets-ui/src/controllers/header-move.controller.ts
Labels: qa:verified

#1143 fix(sheet): text align error when test wrap
  packages/engine-render/src/components/docs/document.ts
Labels: qa:verified

#1154 fix(sheet): #1088 columns have horizontal cells,merge cells are retained when columns are deleted
  packages/sheets/src/controllers/merge-cell.controller.ts
Labels: qa:verified

#1112 fix: some bugs in autofill
  packages/sheets-ui/src/services/auto-fill/rules.ts
  packages/sheets-ui/src/services/auto-fill/tools.ts
  packages/sheets-ui/src/services/clipboard/clipboard.service.ts
  packages/sheets-ui/src/services/clipboard/copy-content-cache.ts
  packages/sheets-ui/src/views/operate-container/AutoFillPopupMenu.tsx
Labels: qa:verified

#1093 fix(sheet): invalid merged cell insertion range
  packages/sheets/src/commands/commands/insert-range-move-down.command.ts
  packages/sheets/src/commands/commands/insert-range-move-right.command.ts
Labels: qa:verified

#1159 fix: some cell editor issues
  packages/sheets-ui/src/controllers/editor/end-edit.controller.ts
  packages/sheets-ui/src/controllers/editor/start-edit.controller.ts
Labels: qa:verified

#1164 feat(sheet): sheet rename confirm, active next unhidden sheet when delete sheet
  packages/sheets-ui/src/controllers/active-worksheet/active-worksheet.controller.ts
  packages/sheets-ui/src/services/selection/selection-render.service.ts
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/SheetBarTabs.tsx
  packages/sheets-ui/src/views/sheet-bar/sheet-bar-tabs/utils/slide-tab-bar.ts
Labels: qa:verified

#1166 fix(formula): deserializeRangeWithSheet add rangeType
  packages/core/src/sheets/__tests__/reference.spec.ts
  packages/core/src/sheets/reference.ts
Labels: qa:verified

#1160 fix: need to refresh cell editor size after scale
  packages/sheets-ui/src/commands/commands/set-zoom-ratio.command.ts
  packages/sheets-ui/src/commands/operations/set-zoom-ratio.operation.ts
  packages/sheets-ui/src/controllers/editor-bridge.controller.ts
  packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx
Labels: qa:verified

#1165 fix(sheet): freeze wrong scroll
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/controllers/scroll.controller.ts
Labels: qa:verified

#1171 fix(sheet): delete all row,columns alert
  packages/core/src/sheets/column-manager.ts
  packages/core/src/sheets/row-manager.ts
  packages/core/src/sheets/worksheet.ts
  packages/sheets-ui/src/commands/commands/__tests__/add-worksheet-merge.command.spec.ts
  packages/sheets-ui/src/commands/commands/__tests__/auto-fill.controller.spec.ts
  packages/sheets-ui/src/commands/commands/__tests__/create-command-test-bed.ts
  packages/sheets-ui/src/commands/commands/__tests__/hide-row-col-confirm.command.spec.ts
  packages/sheets-ui/src/commands/commands/__tests__/remove-row-col-confirm.command.spec.ts
  packages/sheets-ui/src/commands/commands/__tests__/selection-utils.spec.ts
  packages/sheets-ui/src/commands/commands/__tests__/set-format-painter.command.spec.ts
  packages/sheets-ui/src/commands/commands/hide-row-col-confirm.command.ts
  packages/sheets-ui/src/commands/commands/remove-row-col-confirm.command.ts
  packages/sheets-ui/src/commands/commands/utils/selection-utils.ts
  packages/sheets-ui/src/controllers/menu/delete.menu.ts
  packages/sheets-ui/src/controllers/menu/menu.ts
  packages/sheets-ui/src/controllers/sheet-ui.controller.ts
  packages/sheets-ui/src/locale/en-US.ts
  packages/sheets-ui/src/locale/zh-CN.ts
Labels: qa:verified

#1183 fix: calc repeats error
  packages/sheets-ui/src/services/auto-fill/tools.ts
Labels: qa:verified

#1182 fix(sheet): #1095 the FX content is not cleared after the selected co…
  packages/sheets/src/commands/commands/__tests__/delete-range.command.spec.ts
  packages/sheets/src/commands/commands/__tests__/insert-range.command.spec.ts
  packages/sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
  packages/sheets/src/commands/commands/delete-range-move-left.command.ts
  packages/sheets/src/commands/commands/delete-range-move-up.command.ts
  packages/sheets/src/commands/commands/insert-range-move-down.command.ts
  packages/sheets/src/commands/commands/insert-range-move-right.command.ts
  packages/sheets/src/commands/commands/insert-row-col.command.ts
  packages/sheets/src/commands/commands/remove-row-col.command.ts
  packages/sheets/src/commands/commands/utils/selection-utils.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/__tests__/ref-range.setvice.spec.ts
Labels: qa:verified

#1200 feat(sheet): disable zooming on editing
  packages/core/src/index.ts
  packages/core/src/services/command/command.service.ts
  packages/core/src/services/context/__tests__/context.service.spec.ts
  packages/core/src/services/context/context.service.ts
  packages/design/src/hooks/observable.ts
  packages/find-replace/src/views/dialog/Dialog.tsx
  packages/sheets-ui/src/controllers/sheet-ui.controller.ts
  packages/sheets-ui/src/controllers/shortcuts/view.shortcut.ts
  packages/sheets-ui/src/views/count-bar/ZoomSlider.tsx
Labels: qa:verified

#1196 fix(sheet): cursor unnecessary movement
  packages/engine-render/src/components/docs/text-selection-render-manager.ts
Labels: qa:verified

#1194 fix: render emoji
  examples/src/docs/main.ts
  packages/engine-render/src/basics/tools.ts
  packages/engine-render/src/components/docs/block/paragraph/language-ruler.ts
  packages/engine-render/src/components/docs/block/paragraph/paragraph.ts
Labels: qa:verified

#1228 fix: fix unhide widget not dispose on worksheet change
  packages/sheets-ui/src/controllers/header-unhide.controller.ts
Labels: qa:verified

#1226 fix(sheet): fix sheet paste command not working
  packages/sheets-ui/src/commands/commands/clipboard.command.ts
  packages/sheets-ui/src/controllers/shortcuts/utils.ts
Labels: qa:verified

#1252 fix(sheet): formula offscreen
  packages/engine-render/src/components/docs/text-selection-render-manager.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/engine.ts
  packages/engine-render/src/thin-engine.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
Labels: qa:verified

#1260 fix(sheet): compare cache error
  packages/engine-formula/src/engine/value-object/array-value-object.ts
Labels: qa:verified

#1238 fix(sheet): sheet name update formula
  packages/engine-formula/src/basics/common.ts
  packages/engine-formula/src/engine/ast-node/reference-node.ts
  packages/engine-formula/src/engine/dependency/dependency-tree.ts
  packages/engine-formula/src/engine/reference-object/base-reference-object.ts
  packages/engine-formula/src/services/current-data.service.ts
  packages/sheets-formula/src/controllers/active-dirty.controller.ts
  packages/sheets-formula/src/controllers/prompt.controller.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets/src/basics/interfaces/mutation-interface.ts
  packages/sheets/src/commands/commands/remove-sheet.command.ts
  packages/sheets/src/commands/mutations/insert-sheet.mutation.ts
  packages/sheets/src/services/ref-range/util.ts
Labels: qa:verified

#1263 fix(sheet): freeze white
  packages/engine-render/src/components/sheets/sheet-skeleton.ts
  packages/sheets-ui/src/controllers/freeze.controller.ts
  packages/sheets-ui/src/controllers/zoom.controller.ts
  packages/sheets-ui/src/services/selection/selection-shape.ts
Labels: qa:verified

#1287 fix: copy formula
  packages/docs/src/commands/commands/clipboard.command.ts
  packages/sheets-ui/src/commands/commands/clipboard.command.ts
Labels: qa:verified
