Repository dream-num/univer, pull requests merged in 2025-03, with the labels that each got.

#4753 fix: issue for autofill not working
  packages/sheets-ui/src/controllers/auto-fill.controller.ts
Labels: qa:verified

#4579 feat: add multi rows& cols menu
  packages/sheets-ui/src/controllers/menu.schema.ts
  packages/sheets-ui/src/controllers/menu/insert.menu.ts
  packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
  packages/sheets-ui/src/locale/en-US.ts
  packages/sheets-ui/src/locale/fa-IR.ts
  packages/sheets-ui/src/locale/fr-FR.ts
  packages/sheets-ui/src/locale/ru-RU.ts
  packages/sheets-ui/src/locale/vi-VN.ts
  packages/sheets-ui/src/locale/zh-CN.ts
  packages/sheets-ui/src/locale/zh-TW.ts
  packages/sheets/src/commands/commands/__tests__/insert-remove-rows-cols.command.spec.ts
  packages/sheets/src/commands/commands/insert-row-col.command.ts
  packages/sheets/src/commands/commands/utils/selection-utils.ts
  packages/sheets/src/controllers/basic-worksheet.controller.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/ref-range/__tests__/utils.spec.ts
  packages/sheets/src/services/ref-range/util.ts
  packages/sheets/src/services/selections/selection.service.ts
  packages/ui/src/components/menu/desktop/Menu.tsx
  packages/ui/src/services/contextmenu/contextmenu.service.ts
  packages/ui/src/views/components/context-menu/ContextMenu.tsx
Labels: qa:verified

#4771 fix(sheets-conditional-formatting): correct bottom percent rank calculation
  packages/sheets-conditional-formatting/src/models/calculate-unit-v2/__test__/calculate.highlight.spec.ts
  packages/sheets-conditional-formatting/src/models/calculate-unit-v2/__test__/test.util.ts
  packages/sheets-conditional-formatting/src/models/calculate-unit-v2/highlight-cell-calculate-unit.ts
Labels: qa:verified

#4776 fix(sheets-data-validation): data validation valid error on custom formula
  packages/core/src/services/undoredo/undoredo.service.ts
  packages/core/src/shared/rectangle.ts
  packages/sheets-data-validation-ui/src/controllers/dv-reject-input.controller.ts
  packages/sheets-data-validation-ui/src/views/components/detail/index.tsx
  packages/sheets-data-validation/src/services/dv-cache.service.ts
  packages/sheets-data-validation/src/services/dv-custom-formula.service.ts
  packages/sheets-formula/src/services/register-other-formula.service.ts
  packages/sheets-hyper-link/src/commands/commands/add-hyper-link.command.ts
  packages/sheets-hyper-link/src/commands/commands/update-hyper-link.command.ts
  packages/sheets-ui/src/controllers/editor/editing.render-controller.ts
  packages/sheets/src/commands/commands/set-range-values.command.ts
  packages/sheets/src/index.ts
  packages/sheets/src/services/sheet-interceptor/sheet-interceptor.service.ts
  packages/slides-ui/src/services/slide-editor-bridge.service.ts
Labels: qa:verified

#4238 fix(formula): formula update after hide row column
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts-snapshots/formula-filter-row-current-worksheet-chromium-linux.png
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts-snapshots/formula-filter-row-current-worksheet-ci-chromium-linux.png
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts-snapshots/formula-filter-row-other-worksheet-chromium-linux.png
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts-snapshots/formula-filter-row-other-worksheet-ci-chromium-linux.png
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts-snapshots/formula-hide-row-current-worksheet-chromium-linux.png
  e2e/visual-comparison/sheets/sheets-formula-related.spec.ts-snapshots/formula-hide-row-current-worksheet-ci-chromium-linux.png
  packages-experimental/debugger/src/controllers/e2e/e2e.controller.ts
  packages/engine-formula/src/basics/common.ts
  packages/engine-formula/src/controller/calculate.controller.ts
  packages/engine-formula/src/index.ts
  packages/engine-formula/src/models/formula-data.model.ts
  packages/engine-formula/src/services/current-data.service.ts
  packages/sheets-filter-ui/package.json
  packages/sheets-filter-ui/src/commands/commands/__tests__/sheets-filter.command.spec.ts
  packages/sheets-filter-ui/src/commands/operations/__tests__/sheets-filter.operation.spec.ts
  packages/sheets-filter-ui/src/controllers/__tests__/sheets-filter.menu.spec.ts
  packages/sheets-filter-ui/src/services/__tests__/sheets-filter-panel.service.spec.ts
  packages/sheets-filter/package.json
  packages/sheets-filter/src/plugin.ts
  packages/sheets-filter/src/services/sheet-filter-formula.service.ts
  packages/sheets-formula-ui/src/controllers/__tests__/update-formula.controller.spec.ts
  packages/sheets-formula/src/controllers/active-dirty.controller.ts
  packages/sheets-formula/src/controllers/trigger-calculation.controller.ts
  packages/sheets-formula/src/controllers/update-formula.controller.ts
  packages/sheets/src/controllers/basic-worksheet.controller.ts
  pnpm-lock.yaml
Labels: qa:verified

#4787 fix(docs-ui): select all on empty doc
  packages/docs-ui/src/commands/commands/doc-select-all.command.ts
Labels: qa:verified

#4775 fix: [Perf] remove unnecessary `ctx.font =` calls, and avoid drawing glyphs outside the viewBounds.
  e2e/perf/scroll.spec.ts
  package.json
  packages-experimental/debugger/src/controllers/e2e/e2e.controller.ts
  packages/core/src/sheets/sheet-skeleton.ts
  packages/engine-render/src/components/docs/doc-component.ts
  packages/engine-render/src/components/docs/document.ts
  packages/engine-render/src/components/docs/extensions/font-and-base-line.ts
  packages/engine-render/src/components/docs/layout/shaping-engine/font-cache.ts
  packages/engine-render/src/components/extension.ts
  packages/engine-render/src/components/sheets/extensions/font.ts
  packages/engine-render/src/components/sheets/extensions/sheet-extension.ts
  packages/engine-render/src/components/sheets/sheet.render-skeleton.ts
  packages/engine-render/src/components/sheets/spreadsheet.ts
  packages/engine-render/src/context.ts
  packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
  packages/sheets-ui/src/index.ts
Labels: performance

#4818 fix: header line
  packages/sheets-ui/src/controllers/render-controllers/freeze.render-controller.ts
  packages/sheets-ui/src/controllers/render-controllers/sheet.render-controller.ts
  packages/sheets-ui/src/services/selection/selection-control.ts
Labels: qa:untested
